### ISSUE TITLE
Update Path Param without Refresh

### ISSUE THREAD

**Issue by rmanzano-TE** [EmilTholin/svelte-routing#100]
Is it possible to update the path param and push the new location to history without causing a page refresh?

For example, if I have: 
`<Route path="/settings/:section" component={AccountSettings} />`

and `AccountSettings` displays distinct components depending on `:section`
I'd like to be able to link to each of those specific components but also allow users to navigate within `AccountSettings` without causing a page refresh due to data fetching that occurs at the top level of `AccountSettings`.

**Comment by EmilTholin** [comment]
Hi @rmanzano-TE!

Yes, the path parameter will be passed to the `Route` component as a prop so you could just listen go by that inside of `AccountSettings`.

```html
<!-- App.svelte -->
<script>
  import { Router, Link, Route } from "svelte-routing";
  import AccountSettings from "./routes/AccountSettings.svelte";
</script>

<Router>
  <nav>
    <Link to="/">Home</Link>
    <Link to="/settings/foo">Foo</Link>
    <Link to="/settings/bar">Bar</Link>
  </nav>
  <div>
    <Route path="/settings/:section" component="{AccountSettings}" />
  </div>
</Router>

<!-- AccountSettings.svelte -->
<script>
  import { onMount } from 'svelte';
  export let section = '';

  onMount(() => {
    // Will only be logged once when navigating
    // between "/settings/foo" and "/settings/bar"
    console.log('AccountSettings was mounted!');
  })
</script>

{#if section === 'foo'}
  <div>Foo</div>
{:else}
  <div>Bar</div>
{/if}
```

**Comment by rmanzano-TE** [comment]
Doh, I was using `<a>` tags, instead of `<Link>` tags. Thanks!
