### ISSUE TITLE
Proposal to have ability to configure routes using javascript object passed as a property to Router.

### ISSUE THREAD

**Issue by quentincaffeino** [EmilTholin/svelte-routing#108]
Guess the title is pretty self explanatory by itself so I would provide several points why this might be helpful:
1. (__This is the main point for me__) When using github/gitlab pages with SPA application, developer has to create copies of index.html for each page as a fallback for Pages cause route resolution works like this: `/about` -> `/about.html`. Modern static pages generators do this by default by pulling the array of routes out of the Router configuration. So this is what I'm trying to accomplish with this proposal: to create some kind of config that could be easily parsed and used to generate those fallback for Pages. Right now I do this by listing all files in `routes/` directory but this approach doesn't work with routes with parameters like route `/task/:id` mentioned above.
2. Not sure if this is a right way to do this but usually slot in Route component is not so useful because I tend to create `routes` folder with components that represent those routes so Route component are always one liner looking something like this: `<Route path="/task/:id" component={Task} />`

Maybe there is another path that we could go to accomplish first point, I would like to hear suggestions and would like to help develop those.

**Comment by EmilTholin** [comment]
Hi @QuentinCaffeino!

I will have to think about this some more, but it sounds like [Sapper](https://sapper.svelte.dev/) would fit your use case. The [`export` command](https://sapper.svelte.dev/docs#Exporting) will create static pages for all your routes.

**Comment by QuentinCaffeino** [comment]
Hello, thanks! Haven't thought of sapper cause I thought it only used with SSR. Thanks, I'll consider it.
