### ISSUE TITLE
Questions about ESM support

### ISSUE THREAD

**Issue by drwpow** [EmilTholin/svelte-routing#109]
Hello! I’m trying to build an ESM-friendly Svelte app using this library + [Svelvet](https://github.com/jakedeichert/svelvet), built on [Snowpack](https://github.com/pikapkg/snowpack).

However, when consuming the entry file in-browser, this line gives a problem:

```js
export { default as Router } from "./Router.svelte";
```

As browsers don’t know how to use `*.svelte` files directly. Now, I know that the recommended approach is to use the Svelte CLI. But in an ESM setup, that’s not always possible (because in ESM, we can even load `svelte-routing` from a CDN; we don’t always have the ability to import it locally, and we can’t run the Svelte CLI on-request in the user’s browser).

So that brings me to a few questions I had about supporting ESM directly for this project:

1. What are the barriers you face in delivering a separate [module entry](https://github.com/rollup/rollup/wiki/pkg.module) where all the `*svelte` files are transpiled to `*.js`? For example do you have to worry about mismatches among Svelte CLI versions? Or is it simply extra work and there hasn’t been a need before ESM yet?
1. In delivering only `*.svelte` files to npm, does this project follow some sort of “best practices” guide for Svelte libraries? The patterns in this library seem to reflect that of others, and I’m wondering if this is outlined anywhere or the community organically just ships `*.svelte` files to npm for ease of use.

Thanks!

**Comment by EmilTholin** [comment]
Hi @dangodev!

1. In this case it's a matter of extra work, and there hasn’t been a need before ESM yet. I'm not entirely sure how to make a Svelte routing library work with shipping it as ESM and not having it be part of your own compiled app.
2. I'm not following a Svelte best practice with this project since I'm not sure how to go about to make it ESM-friendly. E.g. [a simple standalone component of mine is easy to distribute for all targets](https://github.com/EmilTholin/svelte-spinner/blob/f9f8633d572248627eb8f37fe8161b65d5b25777/package.json#L5-L7), but this project is a lot harder.

**Comment by dangodev** [comment]
>I'm not entirely sure how to make a Svelte routing library work with shipping it as ESM and not having it be part of your own compiled app.

That’s a good point—to ship ESM in this library may go against expectations of how a user expects this to work. If you shipped browser-ready ESM, then that means Svelte wouldn’t be able to interpret this as a Svelte component.

Also thanks for linking to svelte-spinner. That’s a good example of something that could either exist as a Svelte component or as a standalone JavaScript module.

Thanks for answering my questions! I’m kind of with you in that maybe this doesn’t make sense to ship as ESM, at least not without a clearer usecase.

**Comment by EmilTholin** [comment]
Closing this as I see no clear way of shipping this library as ESM. Feel free to re-open or comment if there seems to be a way.
