### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by aaronshaf** [EmilTholin/svelte-routing#11]
After including `import { createBrowserHistory } from "svelte-routing";` I get:

```
warning.js:19 Uncaught ReferenceError: process is not defined
    at warning.js:19
    at MyComponent.html:20
```

**Comment by aaronshaf** [comment]
Upgrading rollup fixed it

**Comment by Eglaf** [comment]
@aaronshaf Would you mind telling me, how did you upgrade that?
Thanks.

**Comment by Snewkis** [comment]
Same issue...
How do you upgrade rollup ? `npm i rollup` isn't working

**Comment by EmilTholin** [comment]
Hey @Snewkis!

`npm i rollup` will most likely just re-install the `rollup` version you already have listed as a `devDependency`. You could try `npm i -D rollup@latest` and see if that helps.

**Comment by munsifmulla** [comment]
I am having a similar issue, tried upgrading the rollup, but it didn't work.
I am getting this issue for prepareRoutes from '@curi/router'

**Comment by munsifmulla** [comment]
> I am having a similar issue, tried upgrading the rollup, but it didn't work.
> I am getting this issue for `prepareRoutes` from `@curi/router`

I found a solution by adding pacakge `rollup-plugin-replace` check it out if it helps
`npm install --save-dev rollup-plugin-replace`

update your `rollup.config` file with
`.....
plugins: [
    replace({
      'process.env.NODE_ENV': JSON.stringify( 'production' )
    })
  ]
....`

**Comment by matiaslopezd** [comment]
Hi @munsifmulla! Thanks!

Do you know if 1 year later was fixed? I'm trying to use [popperjs](https://popper.js.org/) but only works with your solution! This is a issue of rollup?

**Comment by LucasGabrielBecker** [comment]
In 2022 i'm facing this same issue when cloning the website starter project, what fixed for me was @munsifmulla recommendation.

**Comment by albert-ramos** [comment]
In 2022, I was facing this issue yesterday, but it was happening because there was some errors in my imported ts files

**Comment by gabriro** [comment]
@[albert-ramos](https://github.com/albert-ramos) I get this issue after I upgraded all the libraries.

`function serve() {
    let server;

    function toExit() {
        if (server) server.kill(0);
    }

    return {
        writeBundle() {
            if (server) return;
            server = require('child_process').spawn('npm', ['run', 'start', '--', '--dev'], {
                stdio: ['ignore', 'inherit', 'inherit'],
                shell: true
            });

            process.on('SIGTERM', toExit);
            process.on('exit', toExit);
        }
    };
}

export default {
    input: 'src/main.js',
    output: {
        sourcemap: !production,
        format: 'iife',
        name: 'app',
        file: 'public/invoice/plus/build/bundle.js',
        inlineDynamicImports: true
    },
    plugins: [
        svelte({
            compilerOptions: {
                // enable run-time checks when not in production
                dev: !production
            }
        }),
        replace({
            preventAssignment: true,
            values: {
                'process.env': JSON.stringify({
                    ...config({path: path.join(__dirname, production ? '/environment/production/.env' : '/environment/dev/.env') }).parsed
                }),
            }
        }),
        // we'll extract any component CSS out into
        // a separate file - better for performance
        css({output: 'bundle.css'}),

        // If you have external dependencies installed from
        // npm, you'll most likely need these plugins. In
        // some cases you'll need additional configuration -
        // consult the documentation for details:
        // https://github.com/rollup/plugins/tree/master/packages/commonjs
        copy({
            targets: [
                {
                    src: "node_modules/pdfjs-dist/build/pdf.worker.min.js",
                    dest: "public/pdfjs"
                },
                {
                    src: "node_modules/pdfjs-dist/cmaps/**/*",
                    dest: "public/pdfjs/cmaps"
                }
            ]
        }),
        resolve({
            browser: true,
            dedupe: ['svelte'],
            preferBuiltins: true
        }),
        builtins(),
        commonjs(),
        ts({
            typescript
        }),
        json({
            compact: true
        }),

        // In dev mode, call `npm run start` once
        // the bundle has been generated
        !production && serve(),

        // Watch the `public` directory and refresh the
        // browser on changes when not in production
        !production && livereload('public'),

        // If we're building for production (npm run build
        // instead of npm run dev), minify
        production && terser()
    ],
    watch: {
        clearScreen: false
    }
};`

**Comment by baisong** [comment]
In 2022, I was trying to use a secret dotenv variable via `process.env.MYVAR` inside a Vite-powered [sveltekit](https://kit.svelte.dev/) app, and learned that the right way to do that now in sveltekit is to [`import { env } from '$env/dynamic/private';`](https://kit.svelte.dev/docs/modules#$env-dynamic-private) within a [`+page.server.js` file's `PageServerLoad()` function](https://kit.svelte.dev/docs/routing#page-page-server-js)
