### ISSUE TITLE
Refreshing a route produces a 404

### ISSUE THREAD

**Issue by chovy** [EmilTholin/svelte-routing#110]
You can see this at https://upvotocracy.com

**Comment by KeramasWiguna** [comment]
https://stackoverflow.com/questions/57339349/svelte-route-gives-me-404
maybe this answer can help

**Comment by chovy** [comment]
you need to redirect all 404s to index.html

**Comment by johnpapa** [comment]
yes ... `sirv` needs the `--single` option to make this work. I added a PR to the main template to help with this. 

this will work

```json
"scripts": {
  "start": "sirv public --single",
  "start:dev": "sirv public --dev --single"
},
```

**Comment by EmilTholin** [comment]
Hi @chovy! Closing this as previous commenters say it's an issue with serving `index.html` for every route and not just the root `/` path. How exactly to do this with nginx, or apache, etc. is outside the scope of this project.
