### ISSUE TITLE
set two paths to the same component

### ISSUE THREAD

**Issue by johnpapa** [EmilTholin/svelte-routing#111]
I'd like to set two paths to one component. The scenario is when you want the default `/` route to redirect to a named route, such as `/dashboard`.

Currently I do this ...

```html
        <Route path="/" component={Dashboard} />
        <Route path="/dashboard" component={Dashboard} />
```

However this isn't ideal as when I read the active route so I can highlight a menu item (so the user knows where they are in the app), the response could be / or /dashboard. If we had a redirect, then the two paths would both end up as /dashboard

Here is the proposed API

```html
        <Route path="/" redirect="/dashboard" />
        <Route path="/dashboard" component={Dashboard} />
```

**Comment by EmilTholin** [comment]
Hi @johnpapa!

I'm a bit hesitant to introducing a `Redirect` component since most users would expect that to work server-side as well.

I would personally opt for handling the redirect server-side separately, and create a custom component for the browser that does something like this:

```html
<!-- Redirect.svelte -->
<script>
  import { onCreate } from 'svelte';
  import { navigate } from 'svelte-routing';

  export let path;

  onCreate(() => {
    navigate(path);
  });
</script>
```

```html
<!-- App.svelte -->
<Route path="/">
  <Redirect path="/dashboard" />
</Route>
<Route path="/dashboard" component={Dashboard} />
```
