### ISSUE TITLE
Lazy loading syntax

### ISSUE THREAD

**Issue by johnpapa** [EmilTholin/svelte-routing#113]
I couldn't find the lazy loading syntax for loading routes/components lazily. Does this feature exist?

**Comment by EmilTholin** [comment]
Hi @johnpapa!

There is no lazy loading of components built into the framework itself for reasons [discussed here](https://github.com/EmilTholin/svelte-routing/pull/12). [`svelte-loadable`](https://github.com/kaisermann/svelte-loadable) works great in conjunction with this library though, so I recommend using that.
