### ISSUE TITLE
How to use svelte in body tag? Disable SSR?

### ISSUE THREAD

**Issue by mdrabinski** [EmilTholin/svelte-routing#119]
How would one register a svelte event handler on the body tag? Server.js is returning this portion of the html and it appears to be outside the scope of svelte.

`<body on:load="{someFunction()}">`

Also, is there any way to disable SSR if it's not needed? 

Thanks.

**Comment by EmilTholin** [comment]
Hi @mdrabinski!

You can use the `svelte:body` tag in a component of yours and it will attach and detach the event listeners from the body automatically.

```html
<svelte:body
  on:mouseenter={handleMouseenter}
  on:mouseleave={handleMouseleave}
/>
```

The SSR of `svelte-routing` is entirely optional. You could just return an empty document from the server and have all the routing take place in the browser if you want to.
