### ISSUE TITLE
Error opening  Microsoft Edge

### ISSUE THREAD

**Issue by vgab18** [EmilTholin/svelte-routing#120]
![image](https://user-images.githubusercontent.com/18479113/77113334-9444cf00-6a65-11ea-8ea0-3f1e4b680830.png)
![image](https://user-images.githubusercontent.com/18479113/77113352-9d35a080-6a65-11ea-9ac7-4921627d674e.png)

here are the screenshot, hope anyone could help me with this issue

**Comment by nih0** [comment]
I think the issue is with the spread operator which is not fully supported on edge.

**Comment by EmilTholin** [comment]
Hi @vgab18!

This is because some of the JavaScript language features used in this library are not supported natively by Microsoft Edge. You have to transpile the code depending of what browsers you want to target, and how to do that differs if you are using Rollup, Webpack, or something else.
