### ISSUE TITLE
was created with unknown prop 'location'

### ISSUE THREAD

**Issue by ligrant** [EmilTholin/svelte-routing#122]
If use:
 `<Route exact path="about"><About /></Route>`
All good.
If use:
`<Route exact path="about" component={About} />`
About.svelte:14 <About> was created with unknown prop 'location'
About.svelte:14 <About> was created with unknown prop 'exact'
### Any ideal?

"svelte": "^3.20.1"
"svelte-routing": "^1.4.2"

**Comment by n0n3br** [comment]
Can you put the app in repl or codesandbox so we can reproduce the error and try fo fix it ?

**Comment by ligrant** [comment]
I use two different ways  to set route:


`<Route path="about" component={About} /> 
`
About.svelte:14 was created with unknown prop 'location'

`<Route path="/"> <Home /></Route> `
Working well

I found something in the bundle.js
1. `(53:4) <Route path="/">`  **home only**
2. `(49:0) <Router>`  **home route and about route created by different way**
3.`const router = new Router`  **when create new router, its looks like only for home route**

**Maybe just use `<Route path="/"> <Home /></Route>` to avoid warning!?**

```
/* src/App.svelte generated by Svelte v3.20.1 */

 const { console: console_1$3 } = globals;
 const file$8 = "src/App.svelte";

 // (53:4) <Route path="/">
 function create_default_slot_2$1(ctx) {
     let current;
     const home = new Home({ $$inline: true });

     const block = {
         c: function create() {
             create_component(home.$$.fragment);
         },
         m: function mount(target, anchor) {
             mount_component(home, target, anchor);
             current = true;
         },
         i: function intro(local) {
             if (current) return;
             transition_in(home.$$.fragment, local);
             current = true;
         },
         o: function outro(local) {
             transition_out(home.$$.fragment, local);
             current = false;
         },
         d: function destroy(detaching) {
             destroy_component(home, detaching);
         }
     };

     dispatch_dev("SvelteRegisterBlock", {
         block,
         id: create_default_slot_2$1.name,
         type: "slot",
         source: "(53:4) <Route path=\\\"/\\\">",
         ctx
     });

     return block;
 }

 
 // (49:0) <Router>
 function create_default_slot$3(ctx) {
     const route0 = new Route({
             props: {
                 path: "/",
                 $$slots: { default: [create_default_slot_2$1] },
                 $$scope: { ctx }
             },
             $$inline: true
         });

     const route1 = new Route({
             props: { path: "about", component: About },
             $$inline: true
         });


 function create_fragment$b(ctx) {
     let current;

     const router = new Router({
             props: {
                 $$slots: { default: [create_default_slot$3] },
                 $$scope: { ctx }
             },
             $$inline: true
         });
}

 }
```

**Comment by ligrant** [comment]
Basically I  just follow the instruction created a svelte app and install the svelte-routing lib, and copy past.
Today I tried recreate the app on sandbox, it's working well. don't know why i got the warning when running on localhost!

maybe just leave it alone or use `<Route exact path="about"><About /></Route>` instead
Any suggest will be appreciated

**### localhost**
<img width="861" alt="Screen Shot 2020-03-23 at 12 39 18 am" src="https://user-images.githubusercontent.com/6111128/77250946-7b276280-6c9f-11ea-97ad-2c328e0c2b0b.png">

**### sandbox**
<img width="860" alt="Screen Shot 2020-03-23 at 12 39 33 am" src="https://user-images.githubusercontent.com/6111128/77250947-7fec1680-6c9f-11ea-8cfb-608934733961.png">

**Comment by GarethOates** [comment]
I get this error if I do:
<Route path="post" component="{Post}" />
but not when I do
<Route path="post"><Post /></Route>

**Comment by BogdanDarius** [comment]
In the About component add:
`export let location;`

**Comment by EmilTholin** [comment]
Hi @ligrant!

You get this warning because the `location` prop is passed to the rendered `component` [in the `Route`](https://github.com/EmilTholin/svelte-routing/blob/99074ef24e038286a115a690a98f613ec20f7806/src/Route.svelte#L42):
```html
<svelte:component this="{component}" location={$location} {...routeParams} {...routeProps}  />
```

This is so that you can make use of the location information in your component:
```html
<!-- App.svelte -->
<Route path="blog" component="{Blog}" />

<!-- Blog.svelte -->
<script>
  import queryString from "query-string";

  export let location;

  let queryParams;
  $: queryParams = queryString.parse(location.search);
</script>

<h1>Blog</h1>
<p>{queryParams.foo}</p>
```

This sadly means that you get a warning if you are not using the passed in `location` prop in your component. I'm not sure how to make this warning go away without making the API more cumbersome.

The `exact` prop should however not be passed to the rendered component, so `About.svelte:14 was created with unknown prop 'exact'` is a bug that we will fix.

**Comment by clintwood** [comment]
@EmilTholin I obviously have the same issue but was thinking that since the `location` prop is not always used by components would it not make sense to rather expose make it available via context/store (IIRC there is `getContext(LOCATION)` or some store).

I'm not super familiar with `svelte-routing` internals but something like:
```html
<!-- Blog.svelte -->
<script>
  import { location } from 'svelte-routing';
  import queryString from "query-string";

  let queryParams;
  $: queryParams = queryString.parse($location.search);
</script>

<h1>Blog</h1>
<p>{queryParams.foo}</p>
```

**Comment by jimmywarting** [comment]
PS use URLSearchParams instead of query-string

**Comment by quantuminformation** [comment]
Also getting this here 

https://github.com/quantuminformation/svelte-firebase-starter

```
  <Route path="register" component="{Register}" />
            <Route path="recover" component="{Recover}" />
            <Route path="signin" component="{Signin}" />
            <Route path="settings" component="{Settings}" />
            <Route path="users" component="{Users}" />
            <Route path=":username" component="{Profile}" />

            <Route path="/" component="{Home}" />```

![image](https://user-images.githubusercontent.com/216566/86222537-acf57280-bb86-11ea-95e4-0de01a79fe63.png)

**Comment by HNazmul** [comment]
I got the same error at the console... My code is also similar this  that is
```
<Route  path="/" component={Homepage} />
<Route path="/add-poll/" component={About} />
```
![Screenshot_84](https://user-images.githubusercontent.com/71649134/153261484-48246dc3-f0a5-4efb-a87c-deedee71a0b9.png)

**Comment by HNazmul** [comment]
hey, @EmilTholin  this package becoming popular. you should fix all of the bugs.  I saw that the latest version is a year ago. please fix the bug

**Comment by talwat** [comment]
I'm having the same exact issue.

**Comment by mkmoisen** [comment]
@EmilTholin What is the solution to this problem?

If we don't use `export let location;` the console debugger shows a warning.

If we do use `export let location;` the IDE shows a warning for unused variable.

This works in some cases:

`<Route path="/"><Home /></Route>`

But it does not work when you have parameters:

`<Route path="/*foo"><Home /></Route>`

Property 'foo' is missing in type '{}' but required in type '{ foo: any; }'.js(2741)

**Comment by krishnaTORQUE** [comment]
Svelte Routing v1.8.0 released.
This issue has been fixed.
View Changelog: https://github.com/EmilTholin/svelte-routing/blob/master/CHANGELOG.md
