### ISSUE TITLE
basepath is not respected in Links

### ISSUE THREAD

**Issue by joshleblanc** [EmilTholin/svelte-routing#124]
The following creates a link to `/bar`, when it should create a link to `/foo/bar`.

```
<Router basepath="/foo">
  <Link to="/bar" />
</Router>
```

**Comment by joshleblanc** [comment]
Alright so it's due to this line in utils.js

```
  // /foo/bar, /baz/qux => /foo/bar
  if (startsWith(to, "/")) {
    return to;
  }
```

So if you make a link to "bar" instead of "/bar", it works fine. Is there a reason for this?

**Comment by elimisteve** [comment]
@joshleblanc If you change `basepath="/foo"` to `basepath="foo"`, with the leading `/` removed, I think it will work!

**Comment by elimisteve** [comment]
Routing to a path that begins with `/` implies that it's an absolute path. It shouldn't be impossible to route people back to the homepage from within a nested/child router!

**Comment by joshleblanc** [comment]
That makes sense, thanks.
