### ISSUE TITLE
SPA + server routes

### ISSUE THREAD

**Issue by pjebs** [EmilTholin/svelte-routing#126]
Thank you for this router lib.

I do have a question. In Sapper, you can set SPA routes that don't use fragments. And you can also configure routes to go directly to the backend.

Q1 Does this library user non-fragment routes?
Q2 Does it also allow routes to go to the backend directly (i.e. load a new page after backend server returns a response)?

**Comment by elimisteve** [comment]
Q1. Yes, it uses paths, not fragments

Q2. Once the backend is configured to host `index.html` whether than a 404 page, yes, `svelte-routing` will navigate the user to that page on load.

**Comment by pjebs** [comment]
If that's the case, is this actually an alternative to sapper? Does it more or less do the same thing?

**Comment by elimisteve** [comment]
svelte-routing provides routing, that's it. Sapper tries to do a lot more than that.

**Comment by EmilTholin** [comment]
Hi @pjebs!

@elimisteve answered your questions really nicely, so I will close this issue. You can open up a new issue if you have more questions!
