### ISSUE TITLE
URL props not getting populated? This may be why...

### ISSUE THREAD

**Issue by elimisteve** [EmilTholin/svelte-routing#127]
So that people can learn from my mistakes! Had an issue where URL props weren't being passed to components, making the props `undefined`.

What I first did wrong:

```js
    <Route path="/p/:id">
      <Project />  // component will not be able to access the `id` prop
    </Route>
```

Also wrong:

```js
    <Route path="/p/:id" let:params>
      <Project />  // same problem
    </Route>
```

Correct:

```js
    <Route path="/p/:id" let:params>
      <Project id={params.id} />
    </Route>
```

Correct _and simple_ (and in the docs :sweat_smile:):

```js
    <Route path="/p/:id" component={Project}>
```

Makes sense, since `Route` can directly access the component you pass it. But I had initially treated the first and last examples here as equivalent.

**Comment by EmilTholin** [comment]
Hi @elimisteve!

Yes, this difference is a bit tricky to convey. Great that you figured it out, and please suggest any improvements to the README to make this difference more apparent if you have any!
