### ISSUE TITLE
How do I use the hashbang?

### ISSUE THREAD

**Issue by clixsoftware** [EmilTholin/svelte-routing#13]
Unable to use the hashbang on the client side. My app is purely client.

**Comment by EmilTholin** [comment]
Hi @clixsoftware!

If you download the [example from this repository](https://github.com/EmilTholin/svelte-routing/tree/master/example) and use the `createHashHistory` function instead of `createBrowserHistory` the router will use hash routing instead:

```javascript
import { createHashHistory } from 'svelte-routing';
import App from './App.html';

createHashHistory();

const app = new App({
  target: document.getElementById('app'),
  hydrate: true
});
```

**Comment by clixsoftware** [comment]
Got it thank you.

**Comment by crazedVic** [comment]
I realize this is super old, but it appears that in recent releases this functionality has been completely removed?
