### ISSUE TITLE
Set page title?

### ISSUE THREAD

**Issue by kevinrenskers** [EmilTholin/svelte-routing#135]
What's the best/recommended way to set a page title for every route? So that the browser tab shows "My app name - {Page title}".

**Comment by hidde** [comment]
I do this with the `documentTitle` feature of [oaf-svelte-routing](https://github.com/oaf-project/oaf-routing), a wrapper that fixes a number of accessibility gaps in `svelte-routing`.

**Comment by kevinrenskers** [comment]
Can you give an example of how to give a title to each page, that doesn't involve mapping a URL to a string inside that `documentTitle` function? I can't map a location like `/user/{my-unique-id}` to a nice page title for example 🤔 

Or in other words, how can each route set a title, that can then be accessed inside the  `documentTitle` function?

**Comment by hidde** [comment]
Here's what I do: https://github.com/w3c/wai-atag-report-tool/blob/master/src/main.js#L8-L25 

The first one is dynamic-ish.

**Comment by EmilTholin** [comment]
Hi @kevinrenskers!

The recommended way is to use the [`svelte:head`](https://svelte.dev/docs#svelte_head) tag in all your top-level components and render a `title` inside of it.

```html
<svelte:head>
  <title>My app name - About</title>
</svelte:head>
```
