### ISSUE TITLE
Error in refresh

### ISSUE THREAD

**Issue by the-einstein** [EmilTholin/svelte-routing#142]
This issue is closed for applications using server. But for single page applications I am having it difficult to find answer to solve my problem.
While using Rollup I could add `-s` at the end of `sirv public`
But what should I use for Webpack

**Comment by EmilTholin** [comment]
Hi @the-einstein!

The Webpack dev server has a similar option called [historyApiFallback](https://webpack.js.org/configuration/dev-server/#devserverhistoryapifallback) that you can use to render the `index.html` file for 404's as well:

```js
module.exports = {
  // ...
  devServer: {
    historyApiFallback: true
  }
};
```
