### ISSUE TITLE
npm run build under nginx routing not working.

### ISSUE THREAD

**Issue by sinistra** [EmilTholin/svelte-routing#144]
I have approx 6 routes in a spa app.
svelte-routing works perfectly with `npm run dev`.

if I build with `npm run build` and then run the app inside an nginx docker container, routes do not work.
eg. 'http://localhost:8080/products' and press enter ... "404 Not Found ... nginx/1.17.7"

does anyone have any ideas on where to look for the problem?

**Comment by dydx-git** [comment]
Yeah, I have the same issue. Did you manage to solve this?

**Comment by sinistra** [comment]
no response here, so refactored using page.js.
Took 2 hours - works perfectly.

**Comment by MrSrsen** [comment]
If I understand it corectlly `npm run build` do not generate physical files in `/public` so nginx is trying to find non existing physical file and fails.

If you want your SPA to work properly you must config your nginx to redirect all calls (with path intact) to `index.html` file. This fixed the same issues with exported Svelte/Sapper application that I was working on.

I don't know how nginx is configured but for Apache correct `.htaccess` config is
```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.html?q=$1 [L,QSA]
```

**Comment by EmilTholin** [comment]
Hi @sinistra!

@MrSrsen is right on the money. You must either configure nginx to serve your `index.html` file for every route, or use [SSR like in the example in this repository](https://github.com/EmilTholin/svelte-routing/blob/4582a86a0c8067c5599a5ca7809933d0012ae9cd/example/server.js#L9-L21).

**Comment by kevin4dhd** [comment]
any example only nginx?
