### ISSUE TITLE
Add the ability to specify class for Link

### ISSUE THREAD

**Issue by Bigaston** [EmilTholin/svelte-routing#147]
Hello!
I want to know if it's possible to add custom class to the generated `a` element created from the link? Or if it's not, if you are going to add this ability?

Thank you!

**Comment by n0n3br** [comment]
I've made pr #123 to fix this 5 months ago, but nobody touched it.

**Comment by quantuminformation** [comment]
There's a lot of forks of this project, any of them active?

**Comment by quantuminformation** [comment]
check out this one
https://github.com/mefechoel/svelte-navigator-fork

would be nice to have collaboration with users of this lib somehow

**Comment by mefechoel** [comment]
@Bigaston you can add custom classes to a `Link`, using the `getProps` prop. Checkout the [NavLink example](https://github.com/EmilTholin/svelte-routing/blob/master/example/src/components/NavLink.svelte) in the example folder.

@quantuminformation thanks for the plug ;) The repo for the project is actually at [https://github.com/mefechoel/svelte-navigator](https://github.com/mefechoel/svelte-navigator), though.

**Comment by quantuminformation** [comment]
@mefechoel you earned your 1st follower, cant say how long for tho, im pretty fussy)

**Comment by Bigaston** [comment]
Okay! Thanks for your awnser!

**Comment by berkaycubuk** [comment]
For quick fix you guys can cover Link content with div or span.
Example:
`<Link to="login"><span class="text-lg text-gray-600 hover:text-gray-700">Login</span></Link>`

**Comment by bskimball** [comment]
Another option:
`<a use:link href="/login" class="px-3">Login</a>`

**Comment by timohausmann** [comment]
I would appreciate a simple class attribute too.

getProps doesn't work inside components unless you make your CSS selector global, otherwise it will be detected as unused thus removed from the CSS bundle by default.

    <style>
        :global(.logo-link) { color: red; }
    </style>
    <h1><Link to="/" getProps={() => ({class: "logo-link"})}>Svelte Web</Link></h1>

**Comment by mefechoel** [comment]
@timohausmann Having a class attribute on the Link would unfortunatly not help with that. Svelte does not treat class props to components as special props and does not recognize them as classnames either. It would still mark them as unused. Using the link action, as described by @bskimball is the only way to get this working proberly.

Maybe a `LinkContainer` component would make sense for these cases with an api similar to this:

```html
<LinkContainer to="login" let:href let:props>
  <a {href} {...props} class="my-link">Login</a>
</LinkContainer>
```

**Comment by timohausmann** [comment]
@mefechoel thanks for the clarification, I'll `use:link` then!

**Comment by EmilTholin** [comment]
Hi @Bigaston!

Since [`1.5.0` all extra properties given to the `Link` component are passed as attributes to the underlying `a` tag](https://github.com/EmilTholin/svelte-routing/pull/128).

**Comment by Bigaston** [comment]
Okay thank you! ^^
