### ISSUE TITLE
Request: Access to current URL from the Router component slot

### ISSUE THREAD

**Issue by SamuelChanMD** [EmilTholin/svelte-routing#149]
Hello,

I noticed in this other issue that we are able to access the current URL location in the Route slot: https://github.com/EmilTholin/svelte-routing/issues/62

It would be nice if we can access it from the Router slot as well.

**Comment by tiramiseb** [comment]
I agree. I have a navbar which is (logically) outside of any Route, but in the Router. I want to change the color of the link corresponding to the current route, in the navbar. I tried to use `class:active={window.location.pathname===href}`, but as you might expect, it won't work...
