### ISSUE TITLE
Is it possible to refresh the page after build?

### ISSUE THREAD

**Issue by darajava** [EmilTholin/svelte-routing#152]
I have figured out how to make page refresh work as expected as per #142. I actually did it a different way, using Rollup like so:

    !production && serve({historyApiFallback: '/index.html'}),

This works great for dev mode, but when I build the package, refreshing the page breaks it when I navigate away from the home route. Is there any way to avoid this behaviour?

**Comment by johnknoop** [comment]
Thanks a lot for the tip about dev mode. That was the problem I was googling, which brought me to this issue.

Regarding your problem: I solved that using an URL rewrite in our CDN. This screenshot is from Azure CDN, but the principle applies to AWS too:

![image](https://user-images.githubusercontent.com/3394270/88443775-ecc41880-ce19-11ea-953a-f364c3eed2ae.png)

**Comment by darajava** [comment]
That works great, thank you!
