### ISSUE TITLE
[Pug]: incompatibility with Pug ?

### ISSUE THREAD

**Issue by lambda0xff** [EmilTholin/svelte-routing#155]
Using Pug to write component templates doesn't seem to work.
In a working application, replacing html markup with pug syntax displays nothing.

Might be due to Pug markup being wrapped inside a template tag ?

**Comment by quantuminformation** [comment]
I don't think this lib is inactive maintenance atm. Probably needs a core team or something. I still use it as it works fine for my needs.

**Comment by EmilTholin** [comment]
Hi @lambda0xff!

Could you provide a minmal reproducible example that I could ideally just clone and `npm install && npm start` to try?

**Comment by lambda0xff** [comment]
That was a while ago and I ended up using another framework altogether.
