### ISSUE TITLE
navigate to previous route? 

### ISSUE THREAD

**Issue by ppedrazzi** [EmilTholin/svelte-routing#159]
I would like to route a user back to their previous page. 

Is there a way to use navigate(previousPage) perhaps using Router location or history?

**Comment by mefechoel** [comment]
There is jo built in way to do this, although it would be nice to have I think. You can use the global browser history using `history.back()`, which the Router should pick up.

**Comment by ppedrazzi** [comment]
Thank you. Makes sense. I'll use history.back() for now.
