### ISSUE TITLE
Nested Routes

### ISSUE THREAD

**Issue by gufoscuro** [EmilTholin/svelte-routing#160]
Hello, is there a way to nest more levels of routes? I've tried this way, without success

```
<Router>
   <Route path="/app">
      <Router basepath="/app">
         <Route path="/dashboard">...</Route>
         <Route path="/foobar">...</Route>
      </Router>
   </Route>
   <Route path="/admin">
      some component
   </Route>
</Router>
```

Thanks in advance!

**Comment by mefechoel** [comment]
Yes, you can. You need to add a wildcard to the parent `Route`s path and remove its `baspath` like so:

```html
<Router>
   <Route path="app/*">
      <Router>
         <Route path="dashboard">...</Route>
         <Route path="foobar">...</Route>
      </Router>
   </Route>
   <Route path="admin">
      some component
   </Route>
</Router>
```

You can also remove the trailing slashes from the `path` props if you like.

Check out [the example app](https://github.com/EmilTholin/svelte-routing/tree/master/example) for a setup, using nested `Router`s.

**Comment by natrayanp** [comment]
I have a master component which has NAV BAR, SIDE MENU & CONTENT AREA.

When a side bar menu item is clicked, content area to be loaded with child component (which should have a route)
example: /dashboard/Landing:   /dashboard/contact:    /dashboard/item:{id}

Iam from Angular and this is quite easy to achieve there, Not sure on how to configure this nested route?
___________________________________
|                    NAV BAR                                 |  
___________________________________
|                       |                                            |
|                       |    <content area>                |
|  SIDE BAR    |   path based on side bar     |    
|    MENU        |                                             |
|                      |  diff compenent to display    |
|___________|_______________________|


<Router>
         <Route path="dashboard/*" >
              <Dashboard>                                                  <--- master component to be given like this?
                  <Router>
                          <Route path="landing">                      <Landing/>                            </Route>     <-- Content area component?
                          <Route path="contact">                       <Contact/>                           </Route>
                          <Route path="item/:id" let:params>     <Items id="{params.id}" />    </Route>
                  </Router>
              </Dashboard>
        </Route>             
        <Route path="login" >
                <Login/>
        </Route>
</Router>

**Comment by EmilTholin** [comment]
Hi @gufoscuro!

Did you solve this? The feedback from @mefechoel is great and is how you should approach this.
