### ISSUE TITLE
[Help Wanted] Rollup and Svelte Routing

### ISSUE THREAD

**Issue by EINazare** [EmilTholin/svelte-routing#161]
Hey guys,

Thank you for your awesome routing plugin for svelte.
I am in the process of creating my first Svelte app, and have used the second way of creating an app from: https://svelte.dev/blog/the-easiest-way-to-get-started
I.e, I have used the following command:
```
npx degit sveltejs/template my-svelte-project
```

After that, I figured that I would also need some sort of a routing system, and decided to go with the `svelte-routing` package.
I've added the following to the project generated by the above command:
```
<!-- App.svelte -->
<script>
  import { Router, Link, Route } from "svelte-routing";
  import Home from "./routes/Home.svelte";
  import About from "./routes/About.svelte";
  import Blog from "./routes/Blog.svelte";

  export let url = "";
</script>

<Router url="{url}">
  <nav>
    <Link to="/">Home</Link>
    <Link to="about">About</Link>
    <Link to="blog">Blog</Link>
  </nav>
  <div>
    <Route path="blog" component="{Blog}" />
    <Route path="about" component="{About}" />
    <Route path="/"><Home /></Route>
  </div>
</Router>
```

```
// main.js
import App from "./App.svelte";

const app = new App({
  target: document.getElementById("app"),
  hydrate: true
});
```

```
<!-- Blog.svelte -->
<h1>This is your Blog page</h1>
<p>How you doing?</p>
```
```
<!-- About.svelte -->
<h1>This is your About page</h1>
<p>How you doing?</p>
```
```
<!-- Home.svelte -->
<h1>This is your Home page</h1>
<p>How you doing?</p>
```

And kept the rollup config from the above command.

The problem that I am having, is the fact that when I run the build command (`npm run build`) and deploy my svelte app to Surge, if I go to any of the above routes (`/blog`, `/about`, `/home`) and refresh the page, it gives me a 404.

I've tried searching for a solution, I've checked the #58 , but it does not help me with my rollup config.

I was hoping maybe you guys could give me a hint, of what should I do - I mean, I read the #58 issue, I understand that somehow I should change the rollup config so that it somehow redirects all routes to the /index.html file, but I do not know how to do this.

Thank you for your time.

Looking for a positive answer 🤗

**Comment by EINazare** [comment]
Ok, followup, I kind of solved this issue by adding a duplicate file of the index.html, named 200.html, based on the surge docs: https://surge.sh/help/adding-a-200-page-for-client-side-routing.

**Comment by jnthnwn** [comment]
this link will help you reroute all requests (`/blog`, `/about`, `/home`): https://www.npmjs.com/package/sirv#optssingle

in your `rollup.config.js` you need to add this option

```
function serve() {
  let server;

  function toExit() {
    if (server) server.kill(0);
  }

  return {
    writeBundle() {
      if (server) return;
      server = require("child_process").spawn(
        "npm",
        ["run", "start", "--", "--dev", "--single"], <-- add the option here
        {
          stdio: ["ignore", "inherit", "inherit"],
          shell: true,
        }
      );

      process.on("SIGTERM", toExit);
      process.on("exit", toExit);
    },
  };
}
```

**Comment by EmilTholin** [comment]
Hi @EINazare!

Sorry for the slow feedback on this. The solution outlined by @jnthnwn is one great way to go about solving this.
