### ISSUE TITLE
Wildcard that includes current path and all below it

### ISSUE THREAD

**Issue by nickyhajal** [EmilTholin/svelte-routing#162]
A couple weeks ago I posted this on a closed issue, but I suppose maybe it's best to open a new issue: 

Is there a way for to make a single route that matches a path _and_ all paths below it?  For example such that  `<Route path="blog/*" component="{Blog}" />` would match both "/blog" and "/blog/*"?

I am trying to do this now with an admin route:

<Route path="admin" component="{AdminLayout}" />

The admin layout has its own router and a consistent sidebar. If I navigate to a sub-page "admin/metrics", the route doesn't match, so I add:

<Route path="admin/*" component="{AdminLayout}" />

Now, if I navigate between subpages, everything is great. But, if you navigate back to "/admin", the UI flashes as it reloads the AdminLayout component

Ideally I could do something like

<Route path="admin*" component="{AdminLayout}" />

Which matches "/admin" and "/admin/<subpages" with a single route, so AdminLayout would be reused between all of them.

Thanks!

**Comment by mefechoel** [comment]
If I understand your issue correctly, then yes, you could just use the built in wildcard mechanism with a nested Router like so:

```html
<Router>
  <Link to="admin">admin</Link>
  <Link to="admin/metrics">metrics</Link>
  <Link to="admin/another-route">admin/another-route</Link>

  <Route path="admin/*">
    <AdminLayout>
      <Router>
        <Route path="/" component={AdminHome} />
        <Route path="metrics" component={Metrics} />
        <Route path="another-route" component={AnotherComponent} />
      </Router>
    </AdminLayout>
  </Route>
</Router>
```

**Comment by EmilTholin** [comment]
Hi @nickyhajal!

Sorry for the slow feedback on this. The solution outlined by @mefechoel is great. Please re-open the issue with more clarifying information if that wasn't what you meant.
