### ISSUE TITLE
Question: Handle the wrong link

### ISSUE THREAD

**Issue by AsinPetrov** [EmilTholin/svelte-routing#166]
How to handle the wrong link? For example, when user requesting link that does not exist, return "Page not found" component.

**Comment by mefechoel** [comment]
You can define a default `Route`, which is rendered when no other `Route` could be matched (see [documentation for `Route` component](https://github.com/EmilTholin/svelte-routing#properties-2)):

```html
<Router>
  <Route path="/" component={Home} />
  <Route path="about" component={About} />
  <!-- A Route without a path prop is a default Route -->
  <Route>
    <h1>404 - Not found</h1>
  </Route>
</Router>
```
