### ISSUE TITLE
Create @types/svelte-routing

### ISSUE THREAD

**Issue by vaclav-stummer-ooo** [EmilTholin/svelte-routing#168]

**Comment by guidobouman** [comment]
Or add it in this project, for that matter. That might be easier. The `@types` repo is for projects that do not provide type by themselves.

**Comment by guidobouman** [comment]
A list of types that should be supported:

- `Router `
- `Link`
- `Route`
- `navigate`
- `link`
- `links`

That's all, right @EmilTholin ?

**Comment by EmilTholin** [comment]
Hi @vaclav-stummer-ooo!

Yes, we should support types, and I agree with @guidobouman that we should probably keep them in this repository directly.

That sounds like the entire API @guidobouman, yes! [There is a nice PR implementing this](https://github.com/EmilTholin/svelte-routing/pull/117/files), but I have never used TypeScript with Svelte so I will have to research it a bit more before I feel comfortable merging it.

**Comment by guidobouman** [comment]
I'll add a review as well. (Work with TS extensively)

**Comment by smmoosavi** [comment]
until merging #117, you can add this [gist] to your project 

[gist]: https://gist.github.com/smmoosavi/4c56234c1c04d6c5e8b502ea5ab5b8f8

**Comment by lpil** [comment]
It would be fab to have this merged, thank you!

**Comment by EmilTholin** [comment]
Types were added to this repository in [this PR](https://github.com/EmilTholin/svelte-routing/pull/117).
