### ISSUE TITLE
Nested routes

### ISSUE THREAD

**Issue by scottbedard** [EmilTholin/svelte-routing#17]
Hi, just a quick question, does this library support nested routers? I'm trying to migrate from Vue's ecosystem and this is something I use quite a bit in my apps.

As an example, an `/account` route might provide a layout for the various child pages, with `/account/security` or `/account/notifications` being nested inside of it with the various forms, etc...

**Comment by EmilTholin** [comment]
Hi @scottbedard!

Yes, if you try the [example project in this repository](https://github.com/EmilTholin/svelte-routing/tree/master/example) you will see that the [Blog route is essentially its own app inside the main app](https://github.com/EmilTholin/svelte-routing/blob/master/example/src/routes/Blog.svelte). You can nest `Router`s as deep as you like.

**Comment by scottbedard** [comment]
Perfect, thanks for pointing me in the right direction!
