### ISSUE TITLE
export activeRoute from Router Componenet

### ISSUE THREAD

**Issue by OmG3r** [EmilTholin/svelte-routing#171]
Hello, I would like to ask why is `activeRoute` is not exported by default in the `Router.svelte` component, that way users will be able to bind into that store, when the SPA is mounted (using `onMount `to subscribe to the store), therefore being able to determine the active route at the `App.svelte` level ( assuming one router) or at whichever file they use the `Router.svelte `for nested routes

**Comment by mefechoel** [comment]
My guess is, that it is just intended to be used internally, so @EmilTholin does not have to make any guaranties about its structure. You can probably get most of the information you need by accessing the current location of the `Router` via the `Route` components. That way the API surface is a lot cleaner and easier to maintain.

**Comment by EmilTholin** [comment]
Hi @OmG3r!

@mefechoel is correct; it's not part of the public API, so it's not exported. [There is a temporary workaround outlined in this issue](https://github.com/EmilTholin/svelte-routing/issues/41), but that was also not a intended API, so we will have to figure out a fitting solution to this.
