### ISSUE TITLE
Pass props with navigate

### ISSUE THREAD

**Issue by jrbrodie77** [EmilTholin/svelte-routing#172]
I'm trying to use navigate to jump to a login component if the user in unauthenticated.  I want to pass a destination URL to the login component after authentication.

Is it possible to pass props to a component that is being navigated to with the navigation function?  (the other way would be to use stores, but this is more straightforward).

thanks!

John

**Comment by mefechoel** [comment]
Hey! Yes that is possible. You can do it by passing an object via the `state` property of the navigation options like so:

```html
<!-- Login.svelte -->
<script>
  import { navigate } from "svelte-routing";

  const handleLogin = () => navigate(
    "/next/path",
    { state: { path: "/prev/path" } },
  );
  // ...
</script>

<!-- ... -->
<button on:click={handleLogin}>Login</button>
```

You can then access the state on the location object. To get the location object you can use the slot of a `Route`, or its `component` prop:

```html
<Router>
  <!-- Use the `location` inside the `Route` slot -->
  <Route path="next/path" let:location>
    <p>{location.state.path}</p>
  </Route>

  <!-- Use the location via the `location` prop, that is passed to `MyComponent` -->
  <Route path="next/path" component={MyComponent} />
</Router>
```

**Comment by mefechoel** [comment]
If you want to check out an example of protecting a Route using a custom component that redirect to a login page and after login back to the original page, see [this repl example](https://svelte.dev/repl/c81d8f3dff584065a82b2d3ea7cd4aee?version=3.31.0) I made for [svelte-navigator](https://github.com/mefechoel/svelte-navigator). It's pretty similar to svelte-routing, so it might be helpful. It uses svelte-navigator hooks to access the location, but that can be achieved by using the `location` slot prop of `Route` as well.

**Comment by EmilTholin** [comment]
Hi @jrbrodie77!

Closing this issue as the solution outlined by @mefechoel works great.

**Comment by jrbrodie77** [comment]
> Hi @jrbrodie77!
> 
> Closing this issue as the solution outlined by @mefechoel works great.

Thanks! I implemented the solution using the state attribute, works great.
