### ISSUE TITLE
<Link> cannot be styled

### ISSUE THREAD

**Issue by Lumca** [EmilTholin/svelte-routing#174]
I have peice of code:
`<div class="nav-link">
                    <Link to="/blog">
                        BLOG
                    </Link>
                    <Link to="/about">
                        ABOUT ME
                    </Link>
            </div>`
It works flawlessly but it is slyled like a link. I want it to style it but whatever I have tried it is still blue with underline.

**Comment by mefechoel** [comment]
My guess is that your css selector does not target the actual a tag... You could try `.nav-link a` or checkout #147 for more info and possible workarounds.

**Comment by Lumca** [comment]
The <span> solved it for me. Thank you.
