### ISSUE TITLE
Link: pass additional attributes/props down to <a> element (#128). Version 1.5.0 brakes <Link> tag.

### ISSUE THREAD

**Issue by Leffffff** [EmilTholin/svelte-routing#180]
Link: pass additional attributes/props down to <a> element (#128). This commit brakes <Link> tag with error "restProps is not defined". 
Line from source of svelte-routing:
<a href="{href}" aria-current="{ariaCurrent}" on:click="{onClick}" {...props} {...$$**restProps**}>

**Comment by krishnaTORQUE** [comment]
Might fixed in latest version
