### ISSUE TITLE
Errors on styling

### ISSUE THREAD

**Issue by rnnyrk** [EmilTholin/svelte-routing#181]
Hi there,

I'd use to boilerplate out of the examples folder which was easy to setup. Although at the moment I started to add styling, I ran into errors `[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)`.

Although the project is still running as expected I would like to know

1. Why the errors appear
2. And of course how to delete them, so I'm sure the project is correctly. I want to expand with Typescript and scss as soon as I have a solid working project

I've already added `import css from 'rollup-plugin-css-only';` to my `rollup.config.js`. So replaced the css part from the example project for this:

```javascript
      svelte({
        compilerOptions: {
          hydratable: true,
          // css: css => {
          //   css.write("public/bundle.css");
          // }
        }
      }),
      css({ output: 'bundle.css' }),
```

Unfortunately it didn't help.
Can you help me forward? 

<img width="1382" alt="Screenshot 2021-01-21 at 23 21 29" src="https://user-images.githubusercontent.com/4519142/105419894-b9830a80-5c3f-11eb-8b3f-10e893fab25f.png">

**Comment by mefechoel** [comment]
I think this actually is a problem with the example setup...

Try adding `css({ output: false })` to the server bundle plugins after the svelte section. Also changing the start script in `package.json` to `"start": "npm run build && run-p watch server"` helped prevent some errors during the startup of the dev build.

**Comment by rnnyrk** [comment]
Thanks. Fixed the issue. Might worth a update PR to the example directory? Also worth sending a PR with an example to support Typescript and SCSS?

**Comment by mefechoel** [comment]
Yeah, go for it! I think you should leave out ts and scss though to keep it simple... I think it's just meant as a basic example to get started quickly...
