### ISSUE TITLE
Not specifying path for Route for getting a unique error page does not work

### ISSUE THREAD

**Issue by nedoxff** [EmilTholin/svelte-routing#184]
Hello! I wanted to create a custom 404 page to show. I saw about three issues on this topic there and all of them suggested to do not include "path" for the last Route element.
Here's my project structure:
![image](https://user-images.githubusercontent.com/65343244/107128349-0583af80-68ce-11eb-9cba-54da4e675c29.png)
And here's App.svelte:
![image](https://user-images.githubusercontent.com/65343244/107128371-2c41e600-68ce-11eb-8474-cf82bed8633a.png)
As you can see, the NotFound route is located on the bottom, and the home page is located on the top.
When I go to /, i get a normal page:
![image](https://user-images.githubusercontent.com/65343244/107128385-47145a80-68ce-11eb-8fcb-a2dd7a20dd76.png)
But when I try to **cause** a 404, i just get a standart 404 error from google (sorry for russian)
![image](https://user-images.githubusercontent.com/65343244/107128396-66ab8300-68ce-11eb-8c7e-a2dd74f278f1.png)
Maybe I'm blind, or maybe it wasn't fixed. Any ideas? 😅

**Comment by atsepkov** [comment]
Just ran into a similar issue myself, the README doesn't seem to do a good job explaining this but you can use wildcards in routes. Change your last route to `<Route path='*' component="{NotFound}" />` and it should work.
