### ISSUE TITLE
routing does not work in vite but it does work in snowpack

### ISSUE THREAD

**Issue by harshmandan** [EmilTholin/svelte-routing#194]
### Describe the bug

I tried porting my project from snowpack to Vite but the `navigate` part isn't working in the dev mode. Its working fine when I'm building and `serve`-ing it. Another weird thing is that when I was using snowpack only the root route (in local env) would work, but with vite I can directly go to say `localhost:3000/auth/login`. (Ofc in production you would serve the index.js page for the 404, and it would work). The URL changes in the address bar of my browser, but the page does not change,

### Reproduction

I've created a repo here: [Link to repo](https://github.com/harshmandan/vite-svelte-navigate)
Just clone it, run `npm i` and just go to localhost:3000. You'll get stuck at loading. 
Expected behavior is to go to the login page.
You will see the changed url in the address bar as well.
Refreshing the page or visit `localhost:3000/auth`
You'll be shown a link which navigates you to homepage.
Again you'll see that the url changes and content does not, and you can verify this now by refreshing the page and seeing the new content.

### System Info

```node
latest vite.
svelte
svelte-routing
```

**Comment by harshmandan** [comment]
Okay an update on this. `Link` works. Neither `navigate` not `use:link` works. Can you please check what's wrong?

**Comment by sidharthramesh** [comment]
Related to #204 Solution in :#200
