### ISSUE TITLE
Svelte Routing with types for TypeScript

### ISSUE THREAD

**Issue by Arkaraj** [EmilTholin/svelte-routing#196]
So i was using typescript to build a project and i  was using svelte, as this doesn't have for specific types a npm i --save-dev @types/svelte-routing, add a new declaration index.d.ts file containing `declare module 'svelte-routing',  would be nice addition to make svelte work on typescript

**Comment by clintwood** [comment]
PR #117 is a well defined set of types for `sevlte-routing`! 

@EmilTholin can PR #117 be merged please - have you abandoned this repo - last update was 31st Dec 2020?
