### ISSUE TITLE
Question: Can I send some data when using navigate?

### ISSUE THREAD

**Issue by harshmandan** [EmilTholin/svelte-routing#197]
Say I want to navigate the user to the login page because the token is now invalid. I would like to show a popup for the same on the login page. So can I send some data while navigating or should I just use URL parameters?

**Comment by itsfarseen** [comment]
There is a `state` argument that you can pass to navigate. I think you will be able to access it using `history.state` (https://developer.mozilla.org/en-US/docs/Web/API/History/state)

**Comment by krishnaTORQUE** [comment]
`navigate("/next-page", { replace: bool, state: object });`
