### ISSUE TITLE
What is the correct way to forward events when using `<Route component={..}>`?

### ISSUE THREAD

**Issue by itsfarseen** [EmilTholin/svelte-routing#198]
How to convert the following to `<Route component={..}>`?
```svelte
<Button on:foo={fooHandler}/>
```
I tried the following but `fooHandler` was not called: 
```svelte
  <Router>
    <Route component={Button} on:foo={fooHandler} />
    <Route component={Button} onFoo={fooHandler} />
  </Router>
```

Here is a minimal code example:
https://codesandbox.io/s/lucid-archimedes-wem4x?file=/App.svelte

**Comment by EmilTholin** [comment]
Hi @itsfarseen!

If you are interested in the events of your `component` I would render it as a child to `Route` instead:

```svelte
<Router>
  <Route>
    <Button on:foo={fooHandler} />
  </Route>
</Router>
```

**Comment by itsfarseen** [comment]
Thanks!
