### ISSUE TITLE
Route doesn't get rendered when calling `navigate()`

### ISSUE THREAD

**Issue by itsfarseen** [EmilTholin/svelte-routing#199]
Code:
```svelte
<script lang="ts">
  import { Route, Router, navigate } from "svelte-routing";
</script>

<main>
  <button on:click={() => navigate("/")}>Home</button>
  <button on:click={() => navigate("/foo")}>Foo</button>
  <button on:click={() => navigate("/bar")}>Bar</button>
  <Router>
    <Route path="/foo">Foo</Route>
    <Route path="/bar">Bar</Route>
    <Route>Home</Route>
  </Router>
</main>

<style>
</style>
```

Here, the Route corresponding to the browser url at the time of page load is correctly rendered.
When clicking any of the buttons, browser url changes, but the `Router` still renders the old `Route`.
Hitting F5 or entering the url in browser address bar and hitting enter causes the `Route` to be rendered correctly.

Minimal repro: https://codesandbox.io/s/distracted-star-uhss6?file=/src/App.svelte:0-410

**Comment by EmilTholin** [comment]
Hi @itsfarseen!

Your code works if used in [the `example` project in this repository](https://github.com/EmilTholin/svelte-routing/tree/master/example):

https://user-images.githubusercontent.com/11573167/116050251-8e151f00-a677-11eb-9244-75e2231e9d22.mp4

It seems like it might be an issue with CodeSandbox.

**Comment by itsfarseen** [comment]
I see. It doesn't work locally either. 
Could this be because I'm using Vite instead of Rollup?

PS: Just checked and found out that it works when I do `yarn build` instead of the dev server.

**Comment by marcus-wishes** [comment]
Also using the globalHistory doesn't work for me in Vite. When I attach a listener to react on route changed it never gets called. It works for me using Rollup. I was unable to yet figure out why.

**Comment by itsfarseen** [comment]
I went further down the rabbit hole and looks like this is a Vite dev server bug.
https://github.com/vitejs/vite/issues/3155#issuecomment-826942131

Closing :)

**Comment by sidharthramesh** [comment]
Is there any changes that could be done to `svelte-routing` so that vite packages it correctly?

**Comment by itsfarseen** [comment]
@sidharthramesh The full analysis is here https://github.com/vitejs/vite/issues/3155#issuecomment-826942131
The problem is there is mutable global state in `history.js`, and Vite bundles two copies of it. In one file it gets inlined by Vite and in other files it is `import`ed using the url. So the functions in `history.js` called by these files, end up referencing different versions of the state. 
I don't know if this global state is avoidable. 

Also it's not much of a problem in practice I guess because we can disable this optimization and it will stop Vite dev server from inlining files in `svelte-routing`.  And Vite packages things correctly when you do production build.
