### ISSUE TITLE
History is undefined server-side if compiled with generate: 'ssr'

### ISSUE THREAD

**Issue by dschulten** [EmilTholin/svelte-routing#2]
The example uses on-the-fly compilation with `require( 'svelte/ssr/register' );`. When the build is changed to use generate: 'ssr', the history instance in the component is undefined, although server.js creates it.

<details>
<summary>Stacktrace</summary>
<pre>
TypeError: Cannot read property 'location' of undefined
    at data (D:\Dokumente\ws\microfrontends\cart\dist\ssr\bundle.js:512:23)
    at Object._399‍.r.Route._render (D:\Dokumente\ws\microfrontends\cart\dist\ssr\bundle.js:555:24)
    at Object._399‍.r.App._render (D:\Dokumente\ws\microfrontends\cart\dist\ssr\bundle.js:1058:40)
    at Object._399‍.r.App.render (D:\Dokumente\ws\microfrontends\cart\dist\ssr\bundle.js:1039:17)
    at D:\Dokumente\ws\microfrontends\cart\server.js:12:26
    at Layer.handle [as handle_request] (D:\Dokumente\ws\microfrontends\cart\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Dokumente\ws\microfrontends\cart\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Dokumente\ws\microfrontends\cart\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Dokumente\ws\microfrontends\cart\node_modules\express\lib\router\layer.js:95:5)
    at D:\Dokumente\ws\microfrontends\cart\node_modules\express\lib\router\index.js:281:22
</pre>
</details>

I cannot easily switch to on-the-fly compilation because of https://github.com/sveltejs/svelte/issues/967.

There is no workaround ATM.

**Comment by EmilTholin** [comment]
Hi @dschulten! Thank you for reporting this. I will look into it and see if it can be fixed on Monday.

**Comment by EmilTholin** [comment]
Hi @dschulten. I apologize for the absurdly slow response to this issue, but I think I have found the problem.

When generating a SSR-bundle, you need to make sure that you use your topmost component as the entry file, and not the browser entry point where the browser history is created:

```javascript
import svelte from 'rollup-plugin-svelte';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import replace from 'rollup-plugin-replace';
import buble from 'rollup-plugin-buble';

export default {
  input: 'App.html', // App.html instead of index.js
  output: {
    file: 'dist/server_bundle.js', // Generate a separate bundle for the browser and server
    format: 'cjs' // cjs instead of iife for the server
  },
  plugins: [
    svelte({
      generate: 'ssr' // generate a SSR bundle
    }),
    resolve({
      jsnext: true,
      main: true,
      browser: true
    }),
    commonjs(),
    replace({ 'process.env.NODE_ENV': '"development"' }),
    buble(),
  ]
};
```

I will update the example in this repository with a separate SSR bundle and a browser bundle instead, since that is more versatile and more widely used.

**Comment by EmilTholin** [comment]
Sorry for this extremely slow feedback on this, but it was simply not possible to solve this in the previous version.

With `1.0.0` there is no longer a dependency on the `history` library, so the server code can be [completely bundled at compile time](https://github.com/EmilTholin/svelte-routing/blob/0f954fa0b4e3f30665417f04c4b594420ebf97d9/example/rollup.config.js#L38-L55). You can then [pass down the url to the component](https://github.com/EmilTholin/svelte-routing/blob/0f954fa0b4e3f30665417f04c4b594420ebf97d9/example/server.js#L10) and [pass it to the `url` prop of the `Router`](https://github.com/EmilTholin/svelte-routing/blob/0f954fa0b4e3f30665417f04c4b594420ebf97d9/example/src/App.svelte#L8-L12) to force the the application to that url.
