### ISSUE TITLE
404

### ISSUE THREAD

**Issue by doriangrelu** [EmilTholin/svelte-routing#209]
I don't see how to handle the 404 case.
Indeed when I declare a route like this: <Route path="*"> it doesn't work. Is it me who is not doing it the right way?

**Comment by mefechoel** [comment]
You can use a fallback route, which is a route without a `path` prop like this:

```html
<Router>
  <Route path="blog">
    <Blog />
  </Route>
  <!-- ... the rest of your routes -->
  <Route>
    <!-- Your 404 component -->
    <NotFound />
  </Route>
</Router>
```

**Comment by doriangrelu** [comment]
Thx !
