### ISSUE TITLE
[Question] serving .html files

### ISSUE THREAD

**Issue by jaintarun** [EmilTholin/svelte-routing#214]
Please help! Question about routing! 

In Svelte-routing is there a way to do this:

Request = "path-to\xyz.html"
SvelteKit serves content for = "path-to\xyz"

I would like all the links in my SvelteKit site to be ending with .html (because of maintaining SEO rankings)
but return the path without .HTML

I am praying someone here can help :-)

**Comment by krishnaTORQUE** [comment]
For SEO
There is no need to end the url with `.html`.
No search engine require that.
