### ISSUE TITLE
navigate( routeUri ) does not work

### ISSUE THREAD

**Issue by radio-miskovice** [EmilTholin/svelte-routing#219]
App.svelte:
```svelte
<script>
  import { Router, Route, Link, navigate } from 'svelte-routing';
  import Login from './pages/Login.svelte'; // login form - tested without routing, works
  import ContestList from './pages/ContestList.svelte'; // general list component - also tested before
  import Home from './pages/Home.svelte' ; // dummy home page
  export let url='' ;
  
</script>

<Router url="{url}">
  <h1>Hamtest Contest Manager</h1>
  <nav>
    <Link to="/contest/list">Show contest list</Link>
    <Link to="/login">Login</Link>
  </nav>
  <div>
    <Route path="/" component={Home} />
    <Route path="/contest/list" component={ContestList} />
    <Route path="/login" component={Login} />
  </div>
</Router>
```
Home.svelte:
```svelte
<script lang="ts">
import { navigate } from "svelte-routing"

$: navigate('/contest/list', {replace: true })
</script>

<div>
<h3>HOME</h3>
</div>
```
How it works (server runs at port 8888):
1) after load, renders component Home (shows H3 and the HOME text)
2) URL in browser address/search box changes to http://localhost:8888/contest/list - that would be correct
3) but the ContestList component does not render.
4) Both the ContestList and Login will render when clicked on their respective link, but neither of them will render navigate() calls which respond to certain events: Login should switch to ContestList after the user is successfully logged in, ContestList should switch to Login if the user is not logged in.
The above example should reproduce the error with anything used as Login and ContestList components, though.

**Comment by mamolli** [comment]
Was this addressed? I am also struggling with this.

**Comment by ysomad** [comment]
Same problem. Any solutions for this one?

**Comment by airwalk741** [comment]
I am having the same problem.
Temporarily using the code below

```js
  onMount(() => {
    if (accessToken !== null) {
      storeUser.update((user) => {
        return { ...user, isLogin: true };
      });
    } else {
      navigate("/login");
    }
  });
```

**Comment by elliottshort** [comment]
Same issue here. Any fix in sight?

**Comment by krishnaTORQUE** [comment]
I am guessing this issue has been fixed, if you are using latest version.
Please re-open this issue if you are still facing this issue.
