### ISSUE TITLE
Routing separated in different svelte coponents

### ISSUE THREAD

**Issue by jaclas** [EmilTholin/svelte-routing#221]
I have a site built with several svelte components. The main page **Start.svelte,** consists of:

- Header.svelte
- Main.svelte
- Footer.svelte

```
<Header />
<Main menuOnRight="false" />
<Footer pub_date={pubDate} version={ver} />

```

Main.svelte is separated into two components:
- Menu.Svelte
- Body.svelte
```
<div class="main">
    <Menu />
    <Body />
</div>
```

Is it possible to use routing in such a way that the `<Router>` contained in **Menu.svelte** changes the content in **Body.svelte**?

**Comment by krishnaTORQUE** [comment]
**NOT AN ISSUE**
