### ISSUE TITLE
Feature request: NavLink (Like in react-router-dom)

### ISSUE THREAD

**Issue by WhereCanI** [EmilTholin/svelte-routing#222]
I would like to request that you build in a feature like the NavLink from react-router-dom. There you can set an activeClassName that will be used when the URL is equal to the path of the NavLink. This means you don't have to check and calculate which route you are on when refreshing the window and then afterwards set the active class.

**Comment by EmilTholin** [comment]
Hi @WhereCanI!

[The documentation of `Link`](https://github.com/EmilTholin/svelte-routing#link) describes the property `getProps` and how you can use it to build [your own `NavLink`](https://github.com/EmilTholin/svelte-routing/blob/master/example/src/components/NavLink.svelte).
