### ISSUE TITLE
Proxy error with Vite Hot Reload

### ISSUE THREAD

**Issue by hanako-eo** [EmilTholin/svelte-routing#226]
I create an application with svelte on vitejs and I use svelte-routing.

On my App.svelte I have this:
```svelte
<script lang="ts">
  import { Router, Route, Link } from "svelte-routing"
  import Home from "./routes/Home.svelte"
  import NF404 from "./routes/NF404.svelte"

  export let url = ""
</script>

<Router url={url}>
  <nav class="navbar">
    ... (links)
  </nav>
  <div class="container">
    <Route path="*"><NF404/></Route>
    <Route path="/"><Home/></Route>
  </div>
</Router>
```

and when i change this
```svelte
<div class="container">
  <Route path="*"><NF404/></Route>
  <Route path="/"><Home/></Route>
</div>
```
to that
```svelte
<div class="container">
  <Route path="/"><Home/></Route>
  <Route path="*"><NF404/></Route>
</div>
``` 

I have this error

"vite": "^2.9.0"
"svelte": "^3.44.0",
"svelte-routing": "^1.6.0"

![image](https://user-images.githubusercontent.com/53426441/161388152-42c4d778-94b2-4fd4-9a47-483b41c157a5.png)

**Comment by hanako-eo** [comment]
oh and when i change this
```svelte
<div class="container">
  <Route path="/"><Home/></Route>
  <Route path="*"><NF404/></Route>
</div>
```
to that
```svelte
<div class="container">
  <Route path="*"><NF404/></Route>
  <Route path="/"><Home/></Route>
</div>
``` 

I have this

![image](https://user-images.githubusercontent.com/53426441/161388609-a116471b-094c-46b7-beae-eea42ec56d7b.png)

**Comment by krishnaTORQUE** [comment]
Router can only have Route children, that is what I know so far.
Also the 404 page should at the very bottom of the all routes
