### ISSUE TITLE
Bootstrap support for Link

### ISSUE THREAD

**Issue by cybercoder-naj** [EmilTholin/svelte-routing#227]
Add support for custom css classes for the `<a />` tag in the Link component

**Comment by andirady** [comment]
You could use the ``getProps`` for this. E.g.:

```svelte
<script>
  import { Link } from "svelte-routing";

  function getProps() {
    return { class: 'a b c' }
  }
</script>

<Link to="some_page" {getProps}>Some Page</Link>
```

**DISCLAIMER** code not tested.

**Comment by dev-itzarun** [comment]
@andirady 

` <Link to="some_page" class="btn btn-primary" </Link>`

Link supports classes so you can pass required classes like above.

Remember you have included bootstarp in your svelte component

**Comment by krishnaTORQUE** [comment]
Answer by @dev-itzarun
