### ISSUE TITLE
Question: how would you open a route in a new tab?

### ISSUE THREAD

**Issue by DeepBhat** [EmilTholin/svelte-routing#228]
I want to route to a component in a new tab, how do I force that instead of replacing the current page?

**Comment by EmilTholin** [comment]
Hi @DeepBhat!

If I understand your question correctly, you should be able to use a regular anchor tag with the attribute `target` set to `_blank`.

```html
<a target="_blank" href="/a-route">Open a route in a new tab</a>
```

**Comment by DeepBhat** [comment]
Apologies, I don't think I was clear. I meant if I could use `Link` to open a component in a new tab? For example ` <Link to="printers">` opening the `Printers` route in a new tab?

**Comment by EmilTholin** [comment]
I see. If you open a new tab there will be an entirely new history context, so it will not matter if you open the new tab with a regular `a` tag or a `Link`  component (if that were possible). It's simply a limitation of how browsers work, sadly.
