### ISSUE TITLE
define root directory redirection

### ISSUE THREAD

**Issue by Kyovint** [EmilTholin/svelte-routing#229]
Hi! 
I can't have any content in root path, besides, my company dosen't allow me have the login in the root path. so i want to when user types the url (example: localhost:3000) will be redirect to login page (localhost:300/login) automatically. how can i do that? 
thanks

**Comment by rezuan-riyad** [comment]
Did you try onMount() lifecycle in your root-path component? You can navigate to login page whenever root component mounts. @Kyovint

**Comment by krishnaTORQUE** [comment]
This might help

```svelte
<!-- Home.svelte -->
onMount(() => nevigate("/login"))

<!-- App.svelte -->
<Router>
    <Route path="/" component={Home} />
</Router
```
