### ISSUE TITLE
Passing Props to Routes

### ISSUE THREAD

**Issue by EthanHaley** [EmilTholin/svelte-routing#23]
Is there a way to pass props to the children components of a route like you would normally be able to do in Svelte? For example I have a user object I want to pass into my login route for use in the component. Or is the idea that you use stores and keep that info out of the routes?

**Comment by EmilTholin** [comment]
Hi @EthanHaley!

[We explored passing all extra properties on the `Route` to the `component` back when this was a Svelte 2 library](https://github.com/EmilTholin/svelte-routing/pull/14), but we couldn't get it to work properly in SSR. It might be that it's possible now in Svelte 3, but we haven't looked into it yet.

As an alternative for now you can skip the `component` property of the `Route` and render your component as a child instead:

```html
<script>
  import Login from "./components/Login.svelte";

  let user = { id: 1, name: "John Doe" };
</script>

<Router>
  <Route path="login">
    <Login {user} />
  </Route>
  <!-- ... -->
<Router>
```

**Comment by EthanHaley** [comment]
Makes sense, thanks for the quick reply! I'd recommend adding this to the docs just as a quick reference for people getting started.

**Comment by EmilTholin** [comment]
You're welcome! Yeah, it's only mentioned in passing in the documentation right now:

> A component that will render its `component` property ***or children*** when its ancestor `Router` component decides it is the best match.

I will see if I can elaborate on that a bit and make it more clear.

**Comment by vivasvan1** [comment]
<Route path="poshak/:id">
      <Poshak cart={cart}></Poshak>
</Route>

How do i pass cart and id here?
