### ISSUE TITLE
How can i watch for route change in app.js

### ISSUE THREAD

**Issue by julianlaibach** [EmilTholin/svelte-routing#231]
Hey there,
thank you for this awesome Router. In a current Project i need to be able to watch for route changes globally, so i need to have a function in app.js wich checks if a Route has been changed. Currently i see no possible Solution, are there any?
Thanks!

**Comment by amorfati254** [comment]
Hey there, did you find solution to this problem?

**Comment by julianlaibach** [comment]
Hey @amorfati254 sure! I did the following:

in your main JS File in my case: app.js i have the following Lines:

```
import {route} from "./stores/route"

addEventListener("popstate", function (e) {
    onRouteChanged()
});

const onRouteChanged = () => {
    route.set(window.location)    
    scrollTo(0, 0)
}
```

Then i created a route store with the following Lines: 
```
import { writable } from 'svelte/store'

export const route = writable()
```

Now you can do:
```
route.subscribe(route => {
    console.log(route)
});
```

Hope this is helpful!

**Comment by krishnaTORQUE** [comment]
Svelte Routing v1.8 has been released, which added `useLocation` hook, by using it you can track if location or route changes.

**Comment by julianlaibach** [comment]
Awesome thank you for informing!

**Comment by noordawod** [comment]
The only gripe I have with `useLocation` is that it works only on children, not on their parent. And I definitely need it working on the parent... Any workarounds to make it work with parents?
