### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by krishnaTORQUE** [EmilTholin/svelte-routing#236]
Is this project still active?

**Comment by EmilTholin** [comment]
Hi @krishnaTORQUE!

I still merge critical additions (e.g. like [TypeScript support a while back](https://github.com/EmilTholin/svelte-routing/pull/117)), but it's not actively worked on anymore.

I suggest using [SvelteKit](https://kit.svelte.dev/) for new projects as it's a more versatile solution in every possible way.

**Comment by krishnaTORQUE** [comment]
@EmilTholin 
Thanks for the quick response

**Comment by vpalos** [comment]
I'd like to suggest that - while I love and use SvelteKit - `svelte-routing` is still a better choice IMHO for projects where only a *straightforward lightweight routing* library is needed, such as those built on MeteorJS.

So while SvelteKit is awesome, it can't completely replace the need for `svelte-routing`!

**Comment by krishnaTORQUE** [comment]
> I'd like to suggest that - while I love and use SvelteKit - `svelte-routing` is still a better choice IMHO for projects where only a _straightforward lightweight routing_ library is needed, such as those built on MeteorJS.
> 
> So while SvelteKit is awesome, it can't completely replace the need for `svelte-routing`!

Another thing I would like to add
What if I would like to use another backend language e.g.  `go` or `rust`?
What I am trying to say is this project is highly needed & very under rated.
Good job & Thanks @EmilTholin ❤️

**Comment by kryptus36** [comment]
Another +1 for "please maintain this" but my reasoning is slightly different: if your routing is highly dynamic, filesystem routing just doesn't cut it.

For one project, I'm actually using this router inside Svelte Kit in places the filesystem router falls short.

**Comment by krishnaTORQUE** [comment]
Hi @EmilTholin 
Why don't you add sponsor button in this project & create a collective on https://opencollective.com
I think it will be very supportive for this project.

**Comment by krishnaTORQUE** [comment]
Hi
I forked svelte-routing > https://github.com/krishnaTORQUE/svelte-routing-next.
And I merged most of the PR from origin repo.
Please let me know if you have any query.
Thanks.

**Comment by kryptus36** [comment]
> Hi I forked svelte-routing > https://github.com/krishnaTORQUE/svelte-routing-next. And I merged most of the PR from origin repo. Please let me know if you have any query. Thanks.

That looks like it was a significant amount of work. Thanks for doing it!

I'm wondering if @EmilTholin would consider giving control of the npm project over to you. The Svelte Router namespace is a bit messy, and this is one of the top search results for "Svelte router".

I'd be happy to help maintain it as well as the more I use Sveltekit the more I realize it's good for simple projects, but if your routing is at all complex it's an absolute nightmare to maintain a filesystem tree several levels deep where every file has the same name.

If we could get everyone interested in a declarative router working together to create a defacto standard, I feel we'd be doing the community a favor.

**Comment by krishnaTORQUE** [comment]
> 



> > Hi I forked svelte-routing > https://github.com/krishnaTORQUE/svelte-routing-next. And I merged most of the PR from origin repo. Please let me know if you have any query. Thanks.
> 
> That looks like it was a significant amount of work. Thanks for doing it!
> 
> I'm wondering if @EmilTholin would consider giving control of the npm project over to you. The Svelte Router namespace is a bit messy, and this is one of the top search results for "Svelte router".
> 
> I'd be happy to help maintain it as well as the more I use Sveltekit the more I realize it's good for simple projects, but if your routing is at all complex it's an absolute nightmare to maintain a filesystem tree several levels deep where every file has the same name.
> 
> If we could get everyone interested in a declarative router working together to create a defacto standard, I feel we'd be doing the community a favor.

@kryptus36 Thanks
@EmilTholin Yes, I will be happy to maintain the original repo, if you want.

**Comment by EmilTholin** [comment]
Thank you @krishnaTORQUE and @kryptus36. I will look into transferring the npm project over to you @krishnaTORQUE next week, I'm busy this weekend.

**Comment by krishnaTORQUE** [comment]
> Thank you @krishnaTORQUE and @kryptus36. I will look into transferring the npm project over to you @krishnaTORQUE next week, I'm busy this weekend.

Hi @EmilTholin 
Just to inform that I am still waiting. 😊

**Comment by krishnaTORQUE** [comment]
Svelte Routing is back
v1.8 has been released
