### ISSUE TITLE
Any event possible for routing in progress?

### ISSUE THREAD

**Issue by GELight** [EmilTholin/svelte-routing#239]
Hi,

Is there a way to find out that a routing change is in progress or complete?
For example ... On calling "navigate()" I do not have a possibility to get an event or whatever to respond to it.

In my concrete example I have an image cursor which is rendered over specific elements.
If I leave those elements I hide this image cursor but if I navigate to other route I never leave my element with the mouse.
So the image-cursor is already rendered on new page/route. 

So on mobile I have to make a click to hide my cursor.
On desktop I have to move my mouse to hide my cursor.

Therefore it would be nice if I could listen on any events from router..... what happens... what is complete etc...

Best regards, 
Mario

**Comment by krishnaTORQUE** [comment]
Svelte Routing v1.8 has been released, which added useLocation, by using it you can track if location or route changes.
