### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by perjo927** [EmilTholin/svelte-routing#241]
Hi, just updated to 1.8.2 and got the following error;

```
Route.svelte?v=313bc6bc:525 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')
    at $$self.$$.update (Route.svelte?v=313bc6bc:525:11)
    at update (chunk-NJX55KFT.js?v=313bc6bc:1136:8)
    at flush (chunk-NJX55KFT.js?v=313bc6bc:1106:9)
```

This line throws:
[Route.svelte#L23](https://github.com/EmilTholin/svelte-routing/blob/master/src/Route.svelte#L23)

Our code looks like so:

```
<div>
  <Route path="/"><HomePage session={$session} /></Route>
</div>
```

**Comment by perjo927** [comment]
It seems like `$$props` doesn't contain everything that's expected:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/2391754/236523097-8871779f-7665-4993-af9a-a9050afaeedd.png">

**Comment by kerolloz** [comment]
Yeah, same issue here after updating to `1.8.3`

**Comment by Bighamster** [comment]
Same issue, had to roll back to version 1.6.0

**Comment by krishnaTORQUE** [comment]
Sorry about that.
This issue has been fixed in v1.8.4.

**Comment by perjo927** [comment]
Thanks, works for me! :)

**Comment by krishnaTORQUE** [comment]
> Thanks, works for me! :)

Welcome
