### ISSUE TITLE
Query string settings related to Link

### ISSUE THREAD

**Issue by ilarkShim** [EmilTholin/svelte-routing#246]
## query string inquiry
```
<Link to="about?language=en&country=US" {getProps}>
```
If the query string is set as above, the values of isPartiallyCurrent and isCurrent are all passed to getProps as false.

  in node_modules/svelte-routing/src/routes/Link.svelte

#### old code
```
  $: isPartiallyCurrent = $location.pathname.startsWith(href);
```

#### modified code
```
  $: isPartiallyCurrent = $location.pathname.startsWith(href.split('?')[0]);
```
I think it should be modified to .

  I modified it with patch-package and am using it.

**Comment by krishnaTORQUE** [comment]
This will make issue if the url contains query string.
It will completely eliminate the query string checking.
