### ISSUE TITLE
Example code does not work with vite/svelte

### ISSUE THREAD

**Issue by brayden-ooi** [EmilTholin/svelte-routing#249]
Hi, I recently setup a project with `vite` + `svelte-ts` with the following dependency versions 

```
    "@sveltejs/vite-plugin-svelte": "^2.4.2",
    "@tsconfig/svelte": "^5.0.0",
    "svelte": "^4.0.3",
    "svelte-check": "^3.4.4",
    "tslib": "^2.6.0",
    "typescript": "^5.0.2",
    "vite": "^4.4.0"
``` 

I tried with the following syntax as according to the example provided but it returned an error.

`<Route path="/" component={Home} />`

The error:

```
Type 'typeof Home__SvelteComponent_' is not assignable to type 'typeof SvelteComponent | AsyncSvelteComponent'.
  Type 'typeof Home__SvelteComponent_' is not assignable to type 'typeof SvelteComponent'.
    Types of construct signatures are incompatible.
      Type 'new (options: ComponentConstructorOptions<Record<string, never>>) => Home__SvelteComponent_' is not assignable to type 'new <Props extends Record<string, any> = any, Events extends Record<string, any> = any, Slots extends Record<string, any> = any>(options: ComponentConstructorOptions<Props>) => SvelteComponent<...>'.
        Types of parameters 'options' and 'options' are incompatible.
          Type 'ComponentConstructorOptions<Props>' is not assignable to type 'ComponentConstructorOptions<Record<string, never>>'.
            Type 'Props' is not assignable to type 'Record<string, never>'.
              Type 'Record<string, any>' is not assignable to type 'Record<string, never>'.
                'string' index signatures are incompatible.
                  Type 'any' is not assignable to type 'never'.ts(2322)
```

However, the syntax below works:

```
<Route path="/">
  <Home />
</Route>
```

I'm not knowledgable enough in the Svelte ecosystem to pinpoint if this is some versioning issue or something went wrong on my end, but I would be happy to submit a PR to update the example code to the non-problematic syntax.

**Comment by krishnaTORQUE** [comment]
Example will not work because it is too old.
There are so many things has been changed.
Example will be removed in next push.

**Comment by rokit** [comment]
@krishnaTORQUE Rather than remove the example, it should be updated. Even the example linked in the readme returns a 404. How is this used now?

**Comment by krishnaTORQUE** [comment]
> @krishnaTORQUE Rather than remove the example, it should be updated. Even the example linked in the readme returns a 404. How is this used now?

Yes I understand it but the example require complete code changes which also require huge amount of time.
I am open for PR.
