### ISSUE TITLE
typescript errors

### ISSUE THREAD

**Issue by rokit** [EmilTholin/svelte-routing#251]
I see typescript support was added in a previous issue, but it doesn't seem to work out of the box. How is this fixed?

![svelte routing ts error](https://github.com/EmilTholin/svelte-routing/assets/1229742/6a97f11d-eb5a-47ec-a4e4-a3505f6356cd)

**Comment by krishnaTORQUE** [comment]
Which version you are using?

**Comment by rokit** [comment]
The one from npm: 2.0.0

**Comment by krishnaTORQUE** [comment]
In this PR https://github.com/EmilTholin/svelte-routing/pull/247
@patricklizon Already fixed it & I checked & working but maybe the issue is still there.
@patricklizon is it possible to double check it?
Thanks

**Comment by patricklizon** [comment]
@krishnaTORQUE The change was not related to the issue.

**Comment by krishnaTORQUE** [comment]
@rokit which svelte version you are using?

**Comment by kryptus36** [comment]
95% sure this is a Svelte version issue. Svelte 4 changed the typing of component classes. I believe the last working version with Svelte 3 was 1.10. Later versions are typed for Svelte 4.

**Comment by rokit** [comment]
I was using Svelte 3.55.1. I followed the [migration guide](https://svelte.dev/docs/v4-migration-guide) to upgrade to version 4, and now it works. Thanks everyone.
