### ISSUE TITLE
Conditional Renders for sidebar

### ISSUE THREAD

**Issue by ioiofadhil** [EmilTholin/svelte-routing#252]
Hello!

I use svelte-routing as my router. But i can't make this conditional working as intended. Is there any way to achieve this kind of implementation? 

Like some kind of
```
<Router>
   <Route path="/"/>
   <BackendLayout>
      <Route path="/admin/blabla"/>
   </BackendLayout/>
</Router>
```

My goal is to prevent the layout to be re-render. Any way to do this?

**Comment by ioiofadhil** [comment]
Turns out i need to do a workaround with a store(). Here's the example

```
<Router {url}>
  <div class="grid grid-cols-12">
    {#if $RouteStore}
      <Sidebar />
    {/if}
    <div class="{$RouteStore ? "col-span-10 p-[32px]" : "col-span-12"} bg-light-white h-screen overflow-y-scroll relative">
      <div>
        <Route path="/">
          <AppConditional><FrontendLayout><Home /></FrontendLayout></AppConditional>
        </Route>
        
        ...
```

In AppConditional, i `!value` the store to trigger the re-render for conditional sidebars.
If there's any easier way to do this, i really really really appriciate the answer! 

Thanks!!

**Comment by kryptus36** [comment]
If I'm not mistaken you are looking for an embedded router.

<Router>
   <Route path="/">
      <Home />
  </Route>

   < Route path="/admin/*">
     <BackendLayout>
        <Router>
          <Route path="/blabla"><AdminDashboard /></Route>
        </Router>
     </BackendLayout/>
   </Route>
</Router>

**Comment by kryptus36** [comment]
I think you want an embedded router...

```html
<Router>
   <Route path="/"><Home /></Route>
   <Route path="/admin/*>
     <BackendLayout>
        <Router>
             <!-- /admin/dashboard -->
            <Route path="/dashboard"><AdminDashboard /></Route>
        </Router>
     </BackendLayout/>
  </Route>
</Router>
```

**Comment by ioiofadhil** [comment]
@kryptus36 Thank you !!!!
