### ISSUE TITLE
Argument of type 'typeof Router' is not assignable

### ISSUE THREAD

**Issue by Bruce-Hopkins** [EmilTholin/svelte-routing#253]
I just installed this package and I'm trying to follow the example code, but for some reason, I get this error: 

```
Argument of type 'typeof Router' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.
  Type 'typeof Router' provides no match for the signature 'new (args: { target: any; props?: any; }): ATypedSvelteComponent'.
```

It also gives these suggestions, but I don't quite understand them.

```
Possible causes:
- You use the instance type of a component where you should use the constructor type
- Type definitions are missing for this Svelte Component. If you are using Svelte 3.31+, use SvelteComponentTyped to add a definition:
  import type { SvelteComponentTyped } from "svelte";
  class ComponentName extends SvelteComponentTyped<{propertyName: string;}> {}js(2345)
```

I tried using the most recent version of Svelte, (4.1.2) and I still get the same issue.

This is my code:

```html
<!-- App.svelte -->
<script>
  import { Router, Link, Route } from "svelte-routing";
  import Overview from "./lib/pages/Overview.svelte";

  export let url = "/";
</script>

<Router {url}>
  <Route path="/" component={Overview} />
  <Route path="/tasks" component={Overview} />
  <Route path="/schedules" component={Overview} />
</Router>
```

Any thoughts on why I'm running into this problem? Am I doing something wrong? Thank you.

**Comment by krishnaTORQUE** [comment]
svelte version?
svelte-routing version?

**Comment by kryptus36** [comment]
@EmilTholin can you please set up an issue template to request users always give version numbers for svelte & svelte-routing

**Comment by cha0sg0d** [comment]
Same here

**Comment by krishnaTORQUE** [comment]
Looking into it.
I still did not get the svelte-routing version. 
I will try to reproduce the example.

**Comment by raph5** [comment]
Same issue with
```json
"svelte": "^3.57.0",
"svelte-routing": "^2.0.0",
```

**Comment by krishnaTORQUE** [comment]
This is the problem.
`svelte-routing` does not support `svelte@3` any more.

**Comment by cha0sg0d** [comment]
> 

good to know, thanks!

**Comment by kryptus36** [comment]
If you are stuck on svelte 3 because of other libs, you can try v 1.10 of svelte-routing. But any bug fixes made since then won't be there. So ymmv.
