### ISSUE TITLE
Link getProps parameter implicitly has an 'any' type, svelte 4.1.2, typescript 5.1.6

### ISSUE THREAD

**Issue by datacutter** [EmilTholin/svelte-routing#254]
Example:
`<Link
        getProps={(linkParams) => {
          console.log(linkParams);
        }}
      >`
Parameter 'linkParams' implicitly has an 'any' type.

Dependencies:
svelte": "^4.1.2",
"svelte-check": "^3.4.6",
"typescript": "^5.1.6"

The problem is declaring Link class that uses deprecated 'SapperAnchorProps' and 'HTMLProps'
Read: [https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/typescript.md#im-getting-deprecation-warnings-for-sveltejsx--i-want-to-migrate-to-the-new-typings](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/typescript.md#im-getting-deprecation-warnings-for-sveltejsx--i-want-to-migrate-to-the-new-typings)

You could rewrite it to:
`import { HTMLLinkAttributes } from 'svelte/elements';`
`export class Link extends SvelteComponent<Omit<LinkProps & HTMLLinkAttributes, "href" >> { }`

But it would get lost 'SapperAnchorProps'.

**Comment by krishnaTORQUE** [comment]
Sorry I did not understand the issue.

**Comment by krishnaTORQUE** [comment]
> 

svelte-routing version?

**Comment by krishnaTORQUE** [comment]
> > Sorry I did not understand the issue.
> 
> The class Link in the file types\Link.d.ts is writed so that the parameters 'linkParams' are of type any and not 'GetPropsParams' in svelte": "^4.1.2"

svelte-routing version?

**Comment by datacutter** [comment]
> svelte-routing version?

"svelte-routing": "^2.0.0"

**Comment by krishnaTORQUE** [comment]
> You mean
> 
> From `getProps?: (linkParams: GetPropsParams) => Record<string, any>;`
> 
> To `getProps?: (linkParams: GetPropsParams) => Record<string, GetPropsParams>;`
> 
> I am open for PR tho.

@datacutter please confirm me. Thanks

**Comment by krishnaTORQUE** [comment]
Thanks for the PR
