### ISSUE TITLE
Are query params supported?

### ISSUE THREAD

**Issue by opensas** [EmilTholin/svelte-routing#26]
Is there some way to get query params like:

```
http://localhost:3000/blog/first?q=query&page=10
```

**Comment by EmilTholin** [comment]
Hi @opensas!

There is currently no functionality in the router itself that does this for you, but you can parse the `search` part of the `window.location` with e.g. [`query-string`](https://github.com/sindresorhus/query-string#readme) if you want.

It will only be available in the browser, so if you are using SSR you need to guard against that.

```html
<!-- About.svelte -->
<script>
  import queryString from "query-string";

  let parsed = {};

  if (typeof window !== 'undefined') {
    parsed = queryString.parse(window.location.search);
  }
</script>

<h1>About</h1>
<p>{JSON.stringify(parsed)}</p>
```

We could take some inspiration from the great library Reach Router and [pass the `location` as a prop to `Route` component](https://github.com/reach/router/blob/master/src/index.js#L201) if that would be helpful.

**Comment by EmilTholin** [comment]
In [1.4.0](https://github.com/EmilTholin/svelte-routing/blob/master/CHANGELOG.md#140) we started to pass the `location` as a prop to the rendered Route `component` and slot.

You could do something like the following to automatically re-render when the query string changes:

```html
<!-- App.svelte -->
<Link to="blog?foo=bar">Blog</Link>
<Route path="blog" component="{Blog}" />

<!-- Blog.svelte -->
<script>
  import queryString from "query-string";

  export let location;

  let queryParams;
  $: queryParams = queryString.parse(location.search);
</script>

<h1>Blog</h1>
<p>{queryParams.foo}</p>
```

**Comment by QuantumInformation** [comment]
Ok so this will not work

`    let promise = getUserProfile(params.username).then(res => {`

For some reasons I thought `params` was magically available, will use location

**Comment by QuantumInformation** [comment]
btw why are you exporting `location` there?
