### ISSUE TITLE
Class properties on Link

### ISSUE THREAD

**Issue by Sebring** [EmilTholin/svelte-routing#27]
I expected class-properties to be supported.

Where
`<Link class="active" ...>`
results in 
`<a class="active" ...>`

---
I'm new to Svelte so I might be wrong on this and missing the knowledge of the obvious way to achieve this.

**Comment by EmilTholin** [comment]
Hey @Sebring!

You're right in that you can't give a `class` property directly to the `Link` component, but you can use the [`getProps` property function](https://github.com/EmilTholin/svelte-routing#link) and use that to return an object with a property `class` that will be added to the underlying anchor tag.

You can check the [`NavLink` in the example project in this repository](https://github.com/EmilTholin/svelte-routing/blob/master/example/src/components/NavLink.svelte) for an example on how to use it.
