### ISSUE TITLE
Add exports to package.json

### ISSUE THREAD

**Issue by noordawod** [EmilTholin/svelte-routing#274]
WIth the most recent changes in Vite, when you run `vite` in a project that has `svelte-routing` as a dependency, you'll get a warning:

```
> vite build --watch

4:18:09 PM [vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

svelte-routing@2.10.0

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
vite v5.0.5 building for production...
```

If you follow the link outlined in the warning, the fix is pretty straightforward - add a few lines in `package.json`:

![Screenshot 2023-12-05 at 16 19 53](https://github.com/EmilTholin/svelte-routing/assets/4129640/7b0ff648-0d8c-4a0d-a133-8315375cf53c)

**Comment by krishnaTORQUE** [comment]
Please check the `CHANGELOG`.
It makes the package fail to recognize in vscode & `npm run check`.

**Comment by krishnaTORQUE** [comment]
I think you missed the `PR Removed` because it was breaking the package.

**Comment by airxnoor** [comment]
So, what you're saying: You prefer not to break npm/vscode while making vite warn about this (after deprecatiion, stop altogether)?

Just wondering why is that? Is there a way to make both sides happy? Maybe there's a way?

**Comment by krishnaTORQUE** [comment]
Correct 
I tried to make both side work but still no luck.
Opening for PR
