### ISSUE TITLE
Special characters in path

### ISSUE THREAD

**Issue by DanBaDo** [EmilTholin/svelte-routing#275]
I'm trying to use something like
```svelte
<Route path="/signup-confirmation-token/:token" let:params>
```
where :token will be a JWT.

The '.' characters in the JWT are preventing the router to works, getting a 404 error on loading.

**Comment by krishnaTORQUE** [comment]
Could you please make a small reproduction. That will be really helpful. Thanks

**Comment by DanBaDo** [comment]
Finally, it was my fault. It was about a misspelled route.
