### ISSUE TITLE
Missing Export Condition

### ISSUE THREAD

**Issue by kensetyr** [EmilTholin/svelte-routing#276]
5:19:48 AM [vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

svelte-routing@2.10.0

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.

**Comment by krishnaTORQUE** [comment]
Please check the CHANGELOG.
I added the PR which breaks the package then I removed it.
