### ISSUE TITLE
PR #277 breaks the package

### ISSUE THREAD

**Issue by n4n0GH** [EmilTholin/svelte-routing#278]
Please revert pull request #277 and rollback to 2.10.0 as 2.11.0 completely breaks compatibility with Vite based bundling.

Setup:
- Vite 5.0.5
- Svelte 4.2.3
- Node 18

Updating the svelte-routing package to 2.11.0 kills the build process with `Error: Missing "./src/history" specifier in "svelte-routing" package` whereas rolling back to exactly 2.10.0 enables the build to finish. Vite dev server also only starts when adding this package to the Vite config like so:

```javascript
optimizeDeps: {
    exclude: ['svelte-routing'],
  },
```

And quite frankly that can't be it as this also _only_ allows the dev server to work, not the build itself.

**Comment by krishnaTORQUE** [comment]
@JohnCuba please have look.

**Comment by JohnCuba** [comment]
@n4n0GH can you please provide an example app where i can reproduce this?

**Comment by n4n0GH** [comment]
@JohnCuba sure, you can clone the repo https://github.com/alchemix-finance/alchemix-v2-frontend and adjust the package.json to use the mentioned packages in my initial post. That should yield the reported behaviour.

**Comment by JohnCuba** [comment]
@n4n0GH The problem is not in this package, you're just import that you shouldn't. Using direct imports like 'package-name/src/history.js' can cause many errors with bundlers. 
So, i recommend you do not import files directly from libs, and if you really need these files - make PR and export them from index.js file.

**Comment by krishnaTORQUE** [comment]
Solution given
