### ISSUE TITLE
Types in `useHistory` and `useRouter` are incorrect

### ISSUE THREAD

**Issue by Curstantine** [EmilTholin/svelte-routing#280]
The [contexts.d.ts](https://github.com/EmilTholin/svelte-routing/blob/26b506ff1a2e72069f797515fa0d27a841e0cbff/types/contexts.d.ts#L11) file defines `useHistory`, `useRouter` as `readable` when they are objects with functions attached to them.

More context:
Since these don't have a subscribe method attached to it, you can't use these functions with svelte's subscribe syntax. And the messy types are annoying to work with. 

![image](https://github.com/EmilTholin/svelte-routing/assets/69104500/7ad36a8f-1065-4194-87f4-beef051f954c)

**Comment by krishnaTORQUE** [comment]
Please raise a PR if you have better option.
Thanks.

**Comment by james-em** [comment]
@krishnaTORQUE 

They are indeed wrong:

**Test**
```
const router = useRouter();
$: console.log(router)
```
**Output**
```
{activeRoute: {…}, base: {…}, routerBase: {…}, registerRoute: ƒ, unregisterRoute: ƒ}
```

**What types say**

```
type ROUTER = RouterProps;
export const useRouter: () => ReturnType<typeof readable<ROUTER>>;

type RouterProps = {
    basepath?: string;
    url?: string;
    viewtransition?: (direction?: string) => Viewtransition;
};
```

It's not really that the given option is not enough, it's simply is incorrect

**Comment by james-em** [comment]
@krishnaTORQUE 

PR: https://github.com/EmilTholin/svelte-routing/issues/280

**Comment by james-em** [comment]
@krishnaTORQUE 

Thanks for merging. Hopefully it will be released soon! :)

I forgot to mention one thing 

```
registerRoute: (route: Omit<RouteConfig, 'default'>) => {};
unregisterRouter: () => {}
```

registerRoute is properly typed but not unregisterRouter. However, there is an issue with it because internally it compares using `===` for exactly same route passed to `registerRoute` but the route is re-initialized by `registerRoute` internally making it impossible to have a working `unregisterRouter`

It would require some internal changes to do something like this:

```
const myRoute = ...
const registeredRoute = registerRoute(myRoute); // Currently returns nothing

// Let's say it would return something
myRoute === registeredRoute
=> false

unregisterRouter(myRoute) // Would fail
unregisterRouter(registeredRoute) // Would work
```

**Comment by krishnaTORQUE** [comment]
> @krishnaTORQUE
> 
> Thanks for merging. Hopefully it will be released soon! :)
> 
> I forgot to mention one thing
> 
> ```
> registerRoute: (route: Omit<RouteConfig, 'default'>) => {};
> unregisterRouter: () => {}
> ```
> 
> registerRoute is properly typed but not unregisterRouter. However, there is an issue with it because internally it compares using `===` for exactly same route passed to `registerRoute` but the route is re-initialized by `registerRoute` internally making it impossible to have a working `unregisterRouter`
> 
> It would require some internal changes to do something like this:
> 
> ```
> const myRoute = ...
> const registeredRoute = registerRoute(myRoute); // Currently returns nothing
> 
> // Let's say it would return something
> myRoute === registeredRoute
> => false
> 
> unregisterRouter(myRoute) // Would fail
> unregisterRouter(registeredRoute) // Would work
> ```

Thanks for the PR.
If there is any other changes require, you can raise PR for that as well.

**Comment by krishnaTORQUE** [comment]
Hi @james-em 
Waiting for your response.

**Comment by james-em** [comment]
> Hi @james-em Waiting for your response.

Thanks for getting back. I do not need to call registerRoute or unregisterRoute for my usage. Just though I should let you know they are not usuable for now outside of the "expected" usage described in the README.
