### ISSUE TITLE
How can I make :slug-(component_name)-:id route

### ISSUE THREAD

**Issue by eturerer** [EmilTholin/svelte-routing#282]
<Route path="/home" component={Home} 
  <Route path="/:slug-p-:id" component={Product} 
  <Route path="/:slug-c-:id" component={Category} 
  <Route path="/:slug-b-:id" component={Brand} 
  <Route path="/"><Home /></Route>

Product component works, others do not work

**Comment by krishnaTORQUE** [comment]
Not an issue
