### ISSUE TITLE
Hide header conditionaly based on route?

### ISSUE THREAD

**Issue by janusdotai** [EmilTholin/svelte-routing#284]
Greetings,

Thanks for this wonderful library.

I was wondering if its possible to hide an entire heading section if a certain route is met?
How would you accomplish this... for example

/admin/*  

everything under this route should get a header

/public/*

everything under this route should not see a header?

![hide header](https://github.com/EmilTholin/svelte-routing/assets/100089505/555db198-ec66-49e1-8357-ea4e346d8fa0)

**Comment by krishnaTORQUE** [comment]
Not an issue.
Create separate header component & attach to those pages where you want.
