### ISSUE TITLE
Not support for typescript or I'm missing something?

### ISSUE THREAD

**Issue by Guidoow** [EmilTholin/svelte-routing#287]
Hello, I migrated my simple svelte app to typescript but I'm not able to implement svelte-routing.

```
<script lang="ts">
    import { Router, Route } from 'svelte-routing';

    const url = ""
</script>

<Router {url}> // ERROR HERE
    <Route path="/" let:params> // ERROR HERE
        <span>"Text"</span>
    </Route>
</Router>
```

Vscode show the error as:

>Argument of type 'typeof Router' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.
  Type 'typeof Router' provides no match for the signature 'new (args: { target: any; props?: any; }): ATypedSvelteComponent'.

>Possible causes:
>- You use the instance type of a component where you should use the constructor type
>- Type definitions are missing for this Svelte Component. If you are using Svelte 3.31+, use SvelteComponentTyped to add a definition:
  import type { SvelteComponentTyped } from "svelte";
  class ComponentName extends SvelteComponentTyped<{propertyName: string;}> {}ts(2345)
  
  
  I really don't know if im missing something or simply is that svelte-routing is not able to be used in typescript.
  Thanks everyone for read!

**Comment by krishnaTORQUE** [comment]
Not a  know issue. Working fine with typescript.

**Comment by Guidoow** [comment]
Don't you know why my project is throwing that error? I'm really stuck.

I tried to temporarily modify the definitions of each component (Router, Route, Link, etc) of this module from "SvelteComponent" to "SvelteComponentTyped"  and it worked fine, but it is not a good practice.

Example: 
```
// [Router.d.ts]
export class Router extends SvelteComponentTyped<RouterProps> {}
```

**Comment by krishnaTORQUE** [comment]
svelte version: ??
svelte-routing version: ??

**Comment by Guidoow** [comment]
"svelte": "^3.55.0",    
 "svelte-routing": "^2.12.0".
 
May help:
  ```
"devDependencies": {
    "@rollup/plugin-commonjs": "^24.0.0",
    "@rollup/plugin-node-resolve": "^15.0.0",
    "@rollup/plugin-terser": "^0.4.0",
    "@rollup/plugin-typescript": "^11.1.6",
    "@tsconfig/svelte": "^3.0.0",
    "rollup": "^3.15.0",
    "rollup-plugin-css-only": "^4.3.0",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.2.0",
    "svelte": "^3.55.0",                                               
    "svelte-check": "^3.6.9",
    "svelte-preprocess": "^5.1.3",
    "svelte-routing": "^2.12.0",
    "tslib": "^2.5.0",
    "typescript": "^4.9.5"
  },

```

**Comment by krishnaTORQUE** [comment]
There you go
`svelte-routing` does not support `svelte v3`

**Comment by Guidoow** [comment]
Thanks, I will consider to test changing my **svelte** version.

Anyways, I would like to let clear that if I change the Type of the components as I detailed above, `svelte-routing` is **_working perfectly fine_**, including `Router`, `Route`, `Link` and even `navigate` and another functions (I did not tried the entire module).
