### ISSUE TITLE
Route do not have a before

### ISSUE THREAD

**Issue by yanyan1716330643** [EmilTholin/svelte-routing#288]
I want to use Route，code like this:
```
<Router>
    {#each routes as route (route.path)}
        <Route path={route.path} component={route.component} before={route.before}/>
    {/each}
</Router>
```
“route.before” is a function return false or true , default return true. if return false do not to route.
if already has functions like "vue route navigation guards"，give an example. 
thinks

**Comment by krishnaTORQUE** [comment]
So this is a feature request & not an issue?

**Comment by krishnaTORQUE** [comment]
No respond so far
