### ISSUE TITLE
Does this work with Svelte 5?

### ISSUE THREAD

**Issue by tgf9** [EmilTholin/svelte-routing#291]
Svelte recently published their Svelte 5 release candidate.

> Svelte 5 is now in the Release Candidate phase. This means that the design of the framework is largely settled, with no anticipated breaking changes between now and the stable release, and that the most egregious bugs have been stomped.

https://svelte.dev/blog/svelte-5-release-candidate

And [Rich offered a few pointers on migrating libs in the Svelte5 RC release announcement](https://www.youtube.com/watch?v=gkJ09joGBZ4&t=9254s)

I was wondering if anyone has gotten this library to work with Svelte 5. Or if the library needs to be updated, I was wondering if there was any info on a timeline for that.

**Comment by krishnaTORQUE** [comment]
I will only update this library when svelte 5 stable release.
For now I dont think there is any breaking change & this library should work on alpha or beta version. (Not tested)

**Comment by tgf9** [comment]
Actually, I just got my project running with Svelte `5.0.0-next.136` and the latest version of this library. Works fine, no problems.
