### ISSUE TITLE
Async component rendering fails

### ISSUE THREAD

**Issue by mrbrianevans** [EmilTholin/svelte-routing#294]
I'm trying to pass an async import of a component to a route so that its only imported when that page loads, but it doesn't work as expected.

## Repoducable example
```svelte
<Route path="/" component={import('./AnotherComponent.svelte')} />
```

## Expected behaviour
Asynchronously import the requested component when the route is requested and display it.

## Actual behaviour
Error thrown
```
Uncaught TypeError: c is not a function        Route.svelte:29:29
```
 points to this line
https://github.com/EmilTholin/svelte-routing/blob/8e8ece084338d16e7ac5376e96116bf22c080b49/src/Route.svelte#L29

## Suggested solution
I think the problem is with the condition:
https://github.com/EmilTholin/svelte-routing/blob/8e8ece084338d16e7ac5376e96116bf22c080b49/src/Route.svelte#L28

This should allow for async components having an OR condition for if the passed component is a promise. This could be something in the form of `'then' in c` or any alternative way of determining if its a promise. This would make the line look something like:
```ts
if (c.toString().startsWith("class ") || 'then' in c) component = c;
```

I'm happy to contribute this as a fix if you approve.

**Comment by krishnaTORQUE** [comment]
From
`<Route path="/" component={import('./AnotherComponent.svelte')} />`

To
`<Route path="/" component={() => import('./AnotherComponent.svelte')} />`

**Comment by mrbrianevans** [comment]
Thank you, that's working for me now. Is that documented anywhere?

**Comment by krishnaTORQUE** [comment]
> Thank you, that's working for me now. Is that documented anywhere?

Great.
I will update docs.
