### ISSUE TITLE
catch-all parameter support

### ISSUE THREAD

**Issue by aherok** [EmilTholin/svelte-routing#31]
Hi!
I'm curious if there's an easy way to catch the whole URL path, including slash character.

E.g. by using single handler component:
```
<Route path="/:path" component={Test} />
```

I want to catch the whole path into the `path` parameter, including slash character, e.g. `/project` and `/project/test`
This behavior is not handled properly by default.

For now I managed to make a dirty workaround:
```
<Route path="/:path" component={PageView} />
<Route path="/:path/:subpath" component={PageView} />
```
Do you have any hint on more proper way to achieve it?

**Comment by EmilTholin** [comment]
Hi @aherok!

You can use the wildcard splat `*` to make a catch-all parameter.

```html
<Router>
  <Route path=":path/*" component={PageView} />
</Router>
```

This would pass a `path` property to the `PageView` component, but we are currently [filtering out the `*` from the route properties](https://github.com/EmilTholin/svelte-routing/blob/f6a538a5d5cb8e74de0f776e7584c81eb1853f7f/src/Route.svelte#L20-L28).

Maybe it could be useful to pass that as a prop as well? Then you would get two properties passed to `PageView`; `path` and `*`.

```html
<!-- PageView.svelte -->
<div>{$$props.path}</div>
<div>{$$props['*']}</div>
```

**Comment by aherok** [comment]
Thanks for quick answer!

Unfortunately this doesn't help. The asterisk doesn't change anything and the `path` param catches only the first URL part.
The `$$props` variable shows only `{path:'projects'}`

**Comment by EmilTholin** [comment]
That's what I said, "we are currently filtering out the `*` from the route properties".

And then I asked "Maybe it could be useful to pass that as a prop as well?"

**Comment by aherok** [comment]
Oh, I didn't get your question.

In some other router package I've seen something like:
```
<Route path="*path" />
```
Which was just catching the whole path to the `path` parameter. Similar option here would be even better than just passing the asterisk alone as it would not require using `$$props` object.

**Comment by EmilTholin** [comment]
Yeah, being able to name the wildcard sounds like a good idea. I will look into if that's feasible to add in the coming days.

**Comment by EmilTholin** [comment]
Thank you for the great suggestion @aherok. The support for naming wildcards was added in `1.1.0`.

```html
<!-- App.svelte -->
<Route path="page/*wildcardName" component={Page} />

<!-- Page.svelte -->
<script>
  export let wildcardName;
</script>

<h1>{wildcardName}</h1>
```
