### ISSUE TITLE
Is there a way to preview and prevent navigation?

### ISSUE THREAD

**Issue by clintwood** [EmilTholin/svelte-routing#33]
Hi love this router - thanks!

Is there a way to prevent navigation based on a cancelable preview of the link to be navigated to?

My use case is a SPA running on mobile and I'd like to catch and prevent the user from exiting the app by hitting the back button (unless they confirm to do so).

**Comment by EmilTholin** [comment]
Hi @clintwood! Thank you for your kind words!

This library is heavily influenced by the great Reach Router, and therefore share many of the same trade-offs (for now), where one is [no history blocking](https://reach.tech/router/credits).

Maybe [`onbeforeunload` could fit you use case](https://stackoverflow.com/questions/821011/prevent-a-webpage-from-navigating-away-using-javascript)?

**Comment by clintwood** [comment]
@EmilTholin, thanks for the quick response!

I'll take a look at `onbeforeunload` - that should work - thanks!
