### ISSUE TITLE
How do I apply scoped styles to 'a' tag generated by Link?

### ISSUE THREAD

**Issue by konclave** [EmilTholin/svelte-routing#36]
I've got a `Nav` component: 

```
<script>
import {Link} from 'svelte-routing';
</script>

<style>
  a {
    color: #bedead;
    text-decoration: underline;
  }
</style>

<nav>
  <a href="somewhere">Get me somewhere</a>
  <Link to="/signin">Sign in</Link>
  <Link to="/signup">Sign Up</Link>
</nav>
```
Is there any way to make scoped `a` styles to be applied to anchors generated by `Link`component?

**Comment by EmilTholin** [comment]
Hi @konclave!

You could use the [`:global`](https://svelte.dev/docs#style) modifier in order to style all anchor tags inside of your `nav`.

```html
<style>
  nav :global(a) {
    color: #bedead;
    text-decoration: underline;
  }
</style>
```

**Comment by konclave** [comment]
but in that case styles become global, not scoped by component.

**Comment by EmilTholin** [comment]
They become "global" inside the `nav` in your component in my example above, which is what you want.

**Comment by konclave** [comment]
No. I want styles become scoped by svelte component, not by HTML tag. Seems like it's not possible, isn't it?

**Comment by EmilTholin** [comment]
They will be scoped by the `nav`, but if that's not enough for some reason you can give the anchor tag inline styles with the [`getProps`](https://github.com/EmilTholin/svelte-routing/blob/master/example/src/components/NavLink.svelte) property.

**Comment by konclave** [comment]
Okay, thank you.

**Comment by marclevetin** [comment]
I'm learning Svelte and stumbled on your library.  This issue was very helpful.  You may want to add it to the documentation if you want more people to pick up the library.

Thanks for the assist!
