### ISSUE TITLE
Optional params

### ISSUE THREAD

**Issue by iamfrntdv** [EmilTholin/svelte-routing#39]
It would be great if there was support of optional params, so there was ability to do something like this:
```
<Router>
  <Route path="page/:id?" component="{Page}" />
</Router>
```
instead of 
```
<Router>
  <Route path="page" component="{Page}" />
  <Route path="page/:id?" component="{Page}" />
</Router>
```

**Comment by EmilTholin** [comment]
Hi @iamfrntdv!

Thank you for the suggestion! This library is heavily influenced by the great Reach Router, and shares the same [trade-offs](https://reach.tech/router/credits). Complex route patterns adds a lot of size and complexity to the router code, so just static paths, params, and trailing wildcard are supported.

The solution you outlined in your second snippet without the `?` is a good way of going about it. The small increase in boilerplate is a good trade-off.
