### ISSUE TITLE
Pulling the params out

### ISSUE THREAD

**Issue by jacwright** [EmilTholin/svelte-routing#4]
It took me some digging around to figure out how to access the params from the matched route. It may be nice to include this in the readme.

```html
<Route path="/:projectId" component={{Project}} />

<!-- Project.html -->
<h1>Project {{ match && match.params.projectId }}</h1>
```

or

```html
<Route path="/:projectId" bind:match="match">
  <h1>Project {{ match && match.params.projectId }}</h1>
</Route>
```

**Comment by EmilTholin** [comment]
Hi @jacwright! Thank you for this. I forgot to add documentation when I added this functionality in `0.2.0`. I took the liberty of using your great examples.

**Comment by alegomez** [comment]
Hi there, first of all thanks for the brilliant work. I haven't been able to pull the params, could you clarify on how it's done?

cheers!

**Comment by EmilTholin** [comment]
Hi @alegomez! Thank you for the kind words!

All the path parameters will be spread on the passed in `component`. [It's only mentioned briefly in the README](https://github.com/EmilTholin/svelte-routing#route) right now, I should try and make that clearer.

```html
<!-- App.svelte -->
<script>
  import Page from './Page.svelte';
</script>

<Router>
  <Route path="page/:id" component="{Page}" />
<Router />

<!-- Page.svelte -->
<script>
  export let id;
</script>

<p>{id} was passed in here!</p>
```

**Comment by alegomez** [comment]
Hi @EmilTholin, thank you very much indeed for your promt reply. I must have missed that line and I guess I was overthinking things a bit.
Cheers!

**Comment by EthanHaley** [comment]
Quick question regarding this question @EmilTholin 

If I'm rendering my routes as 

`<Route path="path">
    <Component {someProps} />
</Route>
`
`<Route path="path/:id">
    <AnotherComponent {someProps} />
</Route>
`

I don't seem to be able to access my **id** prop inside of AnotherComponent using `export let id;`

Do I need to somehow pass the id prop to my child component since I'm not using `component={Component}` in my route? If so what's the proper way to do so? Thanks!

**Comment by EmilTholin** [comment]
Hi @EthanHaley!

If you want to access the path parameter `id` and at the same time pass some extra props to `AnotherComponent` you can pass the extra props to the `Route` component instead.

```html
<Route path="path/:id" component="{AnotherComponent}" foo="foo" bar="bar" />

<!-- AnotherComponent.svelte -->
<script>
  export let id;
  export let foo;
  export let bar;
</script>

<!-- ... -->
```

**Comment by EthanHaley** [comment]
Using this method, I get an undefined error trying to access my extra props.

`<Route path="{route.alias}/:id" component="{RowView}" config="{config}" route="{route}" />`

config and route are objects that I have constructed in my app code, but trying to access them inside of RowView just gives me an undefined error. The id does pass through correctly however.
