### ISSUE TITLE
Preload data before route change (navigation guards)

### ISSUE THREAD

**Issue by bravecow** [EmilTholin/svelte-routing#40]
Navigation guards lets you to fetch data before rendering component.

Vue.js:

https://router.vuejs.org/guide/advanced/navigation-guards.html#in-component-guards
https://router.vuejs.org/guide/advanced/data-fetching.html#fetching-before-navigation

It was very popular ticket for `react-router` but they could not implement it:
https://github.com/ReactTraining/react-router/issues/4407

Use case:

Fetching your root component data takes ~100ms. If you render "blank component" (with placeholders or loaders) you will see screen flashing. With data preload you can show loader on current screen and after data fetching has been completed, redirect / render component with useful information.

**Comment by EmilTholin** [comment]
Hi @bravecow!

Navigation guards are cool, but I'm hesitant to add it to the library as it would be hard to get it to work properly in SSR.

You could create your own route component that only renders the `Route` when a passed in function has finished loading.

**Example**

```html
<!-- AsyncRoute.svelte -->
<script>
  import { onMount } from 'svelte';
  import { Route } from 'svelte-routing';

  export let path;
  export let component;
  export let loadData;

  let data;
  
  onMount(() => {
    loadData().then(res => data = res);
  });
</script>

{#if data}
  <Route {path} {component} {...data} />
{/if}

<!-- App.svelte -->
<script>
  import { Router } from 'svelte-routing';
  import AsyncRoute from './AsyncRoute.svelte';
  import Foo from './Foo.svelte';
  import Bar from './Bar.svelte';
<script>

<Router>
  <AsyncRoute path="foo" component={Foo} loadData={() => Promise.resolve('foo')} />
  <AsyncRoute path="bar" component={Bar} loadData={() => Promise.resolve('bar')} />
</Router>
```

**Comment by EmilTholin** [comment]
Hi @bravecow!

This project is heavily inspired by Reach Router, and therefore share most of its [trade-offs](https://reach.tech/router/credits). Navigation guards would be history blocking and add a lot of complexity to the router for something that could be implemented in user land, and it won't be possible to get it working in a satisfying way for SSR either.
