### ISSUE TITLE
At least "class" prop on Link

### ISSUE THREAD

**Issue by frederikhors** [EmilTholin/svelte-routing#42]
First time with Svelte and svelte-routing.

I read https://github.com/EmilTholin/svelte-routing/issues/27 but I think at least we should allow `class` prop.

Am I very wrong?

**Comment by frederikhors** [comment]
If we need something simple like this:

```html
<Link to="/" class="navbar-brand">Brand</Link>
```

we need to write something like this:

```html
<Link to="/" getProps={()=>{return {class: 'navbar-brand'}}}>Brand</Link>
```

And, apart from verbosity, on every render I have an anonymous function!

It smell like a problem.

**Comment by EmilTholin** [comment]
Hi @frederikhors!

>And, apart from verbosity, on every render I have an anonymous function!

That's not true. Svelte makes inline functions once on component creation.

The `getProps` function is the correct way to give attributes to the underlying `a` element.

**Comment by linvain** [comment]
@EmilTholin
> The `getProps` function is the correct way to give attributes to the underlying `a` element.

So I should add
```
.post :global(.username) {
  font-weight: bold;
}
. . .
<Link to={`/u/${author_id}`} getProps={() => ({ class: "username" })}>{username}</Link>
```
**AND** fix all specificity issues emerged from this EVERYTIME I want to add local styles?
Svelte community won't get anywhere with this.

**Comment by EmilTholin** [comment]
@linvain "Svelte community won't get anywhere with this." - This is not an official library, but a library of my own. Do you think contributors feel like helping you when you talk like this?

If you would have read the documentation you would have seen the [`link` action](https://github.com/EmilTholin/svelte-routing#link-1) which allows you to give whatever attribute to the anchor tag directly.
