### ISSUE TITLE
<Component> was created with unknown prop '*'

### ISSUE THREAD

**Issue by frederikhors** [EmilTholin/svelte-routing#43]
Using something like this:

```html
<Router url="{url}">
    <Route path="about" component="{About}" />
    <Route path="blog/*" component="{Blog}" />
</Router>
```

In `Blog` component I have this warning in console:

```
<BlogPage> was created with unknown prop '*'
```

Can we avoid this?

**Comment by EmilTholin** [comment]
You can give the wildcard a name and export that variable from `Blog`, or you could use `$$props["*"]`.

```html
<Router url="{url}">
  <Route path="about" component="{About}" />
  <Route path="blog/*wildcardName" component="{Blog}" />
</Router>

<!-- Blog.svelte -->
<script>
  export let wildcardName;
</script>
```

You could ask in the Svelte Discord #support channel if there is a way to disable the prop warnings as well.

**Comment by frederikhors** [comment]
Ok.

Anyway, I downloaded the example folder and in that project on blog route I don't have that warning.

**Why?**

**Comment by EmilTholin** [comment]
You probably installed a Svelte version older than [3.4.3](https://github.com/sveltejs/svelte/blob/master/CHANGELOG.md#343).

**Comment by ligrant** [comment]
If use:
 <Route path="about"><About /></Route>
All good.
If use:
<Route exact path="about" component={About} />

About.svelte:14 <About> was created with unknown prop 'location'

Any ideal?

**Comment by SleeplessGamers** [comment]
@EmilTholin Has this issue been fixed for older  versions of svelte. Im currently on version 3.38
