### ISSUE TITLE
Not using an express server

### ISSUE THREAD

**Issue by mihairaulea** [EmilTholin/svelte-routing#47]
Is there any way that this router could work without using the express server? It seems like an overcomplication and a move away from the vailla js approach that svelte proposes.

**Comment by EmilTholin** [comment]
Hi @mihairaulea!

Do you mean if you have to use SSR? No, you don't have to use the SSR capabilities of the library at all if you don't need it. You could just use it in the browser.

**Comment by mihairaulea** [comment]
That was fast! Okay, thanks!
