### ISSUE TITLE
is it possible that a route do not render again when changing to other and come back?

### ISSUE THREAD

**Issue by angelserranoperez** [EmilTholin/svelte-routing#49]
The situation is the following:
When you go to a url through the Link then the component is rendered.
Then you decide to go to another url and come back to the before url.
The question is that if is possible that when you come back to the before url then it would not be rendered again.

For example:
You have 3 pages:
Home
About
Blog
At first you begin in Home and then you go to Blog.
When you are in blog you want to go to about.
In About you want to come back to Blog but **I want that Blog page will not render again.**

I use this structure for routing:
```
<Router>
  <Navbar />
  <div class="container">
    <Route path="/" component={Home} />
    <Route path="/about" component={About} />
    <Route path="/blog" component={Blog} />
  </div>
</Router>
```

In Navbar:
```
<script>
  import { Link } from "svelte-routing";
</script>

<Link to="/">
  <button>Go Home</button>
</Link>
<Link to="/blog">
  <button>Blog</button>
</Link>
<Link to="/about">
  <button>About</button>
</Link>
```

**Comment by Egnus** [comment]
What do you mean with "render"? to remain the state of blog when you leave the component?
As far as I know from the library and the best approachs, when you change routes the component is completely deleted from the DOM, therefore, whenever you come back the component has to be instantiate again.

You should create stores to keep your states so you can return to the same state of blog component, and also you should take a look into `<script context="module">` which is only instantiated once and not in every load of the component. more info https://svelte.dev/docs#script_context_module

**Comment by EmilTholin** [comment]
Hi @angelserranoperez!

There is nothing built-in to this library that would allow you to do this, but you could e.g. have an external store that keeps track of if you have visited the `/blog` path already.

```javascript
// store.js
import { writable } from 'svelte';

const store = writable({
  hasVisitedBlog: false
});

export default store;
```
```html
<!-- Blog.svelte -->
<script>
  import { onDestroy } from 'svelte';
  import store from './store.js';

  onDestroy(() => $store.hasVisitedBlog = true);
</script>

{#if !$store.hasVisitedBlog}
  <!-- Render blog... -->
{/if}
```
