### ISSUE TITLE
axios not working

### ISSUE THREAD

**Issue by elviskudo** [EmilTholin/svelte-routing#51]
Hi Emil, thanks for your library
that's awesome, simple, fast performance

I tried add axios, but showing error like this:
```
[!] Error: Unexpected token (Note that you need rollup-plugin-json to import JSON files)
node_modules/axios/package.json (2:9)
```

how can i solved that?
thanks

**Comment by EmilTholin** [comment]
Hi @elviskudo! Thank you for the kind words, but this isn't really related to `svelte-routing`. You could try and [configure Rollup like in this comment and see if that fixes it](https://github.com/rollup/rollup-plugin-commonjs/issues/28#issuecomment-167934572).

**Comment by elviskudo** [comment]
oh thanks
