### ISSUE TITLE
package not compiled

### ISSUE THREAD

**Issue by shavyg2** [EmilTholin/svelte-routing#53]
This only works if i used degit to download the repo. The package is not compiled when i check it in my node_modules. svelte won't compile modules from npm as it should come published compiled.

can't require .svelte file from node_module folder from index.js in src

**Comment by EmilTholin** [comment]
Stop spamming the issue tracker. This issue is identical to https://github.com/EmilTholin/svelte-routing/issues/52 you opened yesterday.
