### ISSUE TITLE
Re-mount on navigation

### ISSUE THREAD

**Issue by Drabuna** [EmilTholin/svelte-routing#54]
Not sure if this is an issue, or expected behaviour:

I have a route -  `/user/:id` and a component that is responsible for representing that route - `UserPage`
When `UserPage` is loaded for first time, `onMount` is being called.
`UserPage` also contains a bunch of link to other users profiles - who viewed your profile (`a` tag with `use:link`).
When one of those links is clicked, route changes and :id changes, but all inside originally mounted component.  So `onMount` is never called again.
Is this intentional?

**Comment by EmilTholin** [comment]
Hi @Drabuna!

Yes, this is intentional as the `UserPage` would not be destroyed and created again, but rather get new props.

You could e.g. use a reactive statement to run some logic when the `id` changes.

```html
<!-- UserPage.svelte -->
<script>
  export let id;
  
  $: console.log(id);
</script>

<h1>{id}</h1>
```

**Comment by Drabuna** [comment]
Alright, thank you :)

**Comment by bidipeppercrap** [comment]
How can I re-mount every parent navigation? Is there any way?
