### ISSUE TITLE
How to handle "404" or "no match"

### ISSUE THREAD

**Issue by marylychee** [EmilTholin/svelte-routing#55]
How do I try handle a no match ? 

Seeing how react routing https://tylermcginnis.com/react-router-handling-404-pages/ 
I'm curious how might I handle a '404' situation?

**Comment by marylychee** [comment]
ohkay solved it 

used something like this

```


<Router url="{url}">
		<nav>
			<NavLink to="/">home</NavLink>
			<NavLink to="about">about</NavLink>
			<NavLink to="research">research</NavLink>
			<NavLink to="team">team</NavLink>
		</nav>
		<Route path="about" component="{About}" />
		<Route path="research" component="{Research}" />
		<Route path="team" component="{Team}" />
		<Route path="/" component="{Home}" />
		<Route patth="*" component={NoMatch}/>
</Router>
```

**Comment by EmilTholin** [comment]
Hi @marylychee!

That's one way of going about it. You can also do it as it is outlined briefly in the [`Route` documentation](https://github.com/EmilTholin/svelte-routing#route):

> If no `path` is given the `Route` will act as the default that matches if no other `Route` in the `Router` matches.

```html
<Router>
  <Route path="blog" component="{Blog}" />
  <Route path="about" component="{About}" />
  <Route path="/"><Home /></Route>
  <Route component={NotFound} />
</Router>
```

**Comment by marylychee** [comment]
oh thanks yeah that's way simpler! 

Sorry I missed it in the docs!
