### ISSUE TITLE
Cannot destructure property `base` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by jethro91** [EmilTholin/svelte-routing#57]
I found some error in Link.svelte code

my browser console says.
```
Uncaught (in promise) TypeError: Cannot destructure property `base` of 'undefined' or 'null'.
    at instance$2 (Link.svelte:12)
    at init (index.mjs:1224)
    at new Link (Link.svelte:26)
    at create_fragment$4 (page-url.js:24)
    at init (index.mjs:1236)
    at new ChangePassword (ChangePassword.svelte:16)
    at Array.create_if_block$1 (MainLayout.svelte:42)
    at create_fragment$d (AuthLayout.svelte:7)
    at init (index.mjs:1236)
    at new AuthLayout (AuthLayout.svelte:7)

```

Link.svelte
```
....
const { base } = getContext(ROUTER);
....
```

**Comment by EmilTholin** [comment]
Hi @jethro91!

If the result of the expression `getContext(ROUTER)` is `undefined` you have most likely forgotten to use the `Router` component as an ancestor for your `Link` component.

It is recommended to have at least one top level `Router` in the app:

```html
<!-- App.svelte -->
<script>
  import { Router, Link } from "svelte-routing";
</script>

<Router>
  <nav>
    <Link to="/">Home</Link>
    <Link to="about">About</Link>
    <Link to="blog">Blog</Link>
  </nav>
</Router>
```

**Comment by jethro91** [comment]
Update not found any solution 
I just commented out this block code and the error disappear

```
  <Link to="/">
              Back
  </Link>
```

**Comment by orlov-vo** [comment]
It’s same for me. I think it is related with some bug in Svelte - because I can’t read a context in then block of await statement:

```
<Router>
  <Route path=“/”>
    {#await promise then}
      <Link to=“/signup”>DOESNT WORK</Link>
    {/await}
  </Route>
</Router>
```

**Comment by montrealist** [comment]
> It is recommended to have at least one top level `Router` in the app:

Thank you, this was the fix for me! 🙏🏼 

For anyone searching later: running `npm test` with Jest was producing `TypeError: Cannot destructure property 'base' of 'getContext(...)' as it is undefined.` when testing a component importing Link from `svelte-routing`.

Before:
```
import { Link } from "svelte-routing";
<Link to="{to}" getProps="{getProps}">
<slot />
</Link>
```
After: 
```
import { Router, Link } from "svelte-routing";
<Router>
    <Link to="{to}" getProps="{getProps}">
    <slot />
    </Link>
</Router>
```

**Comment by George-Olufemi** [comment]
I have tried all these solutions, it still doesn't work...

What am I most probably not doing right ?
