### ISSUE TITLE
Reload route page returns 404

### ISSUE THREAD

**Issue by POPOEVER** [EmilTholin/svelte-routing#58]
Any plan or existing solution to fix?

**Comment by EmilTholin** [comment]
Hi @POPOEVER!

This is not `svelte-routing` specific, but more related to your server setup. You must make sure your server serves the `index.html` file for all your routes.

If you are using express you can do it like it is done [in the example in this repository](https://github.com/EmilTholin/svelte-routing/blob/master/example/server.js#L7-L21). If you are using `sirv` you can use the `--single` flag.

**Comment by neetjn** [comment]
Does this project support client side routing? I tried using a hash bang as the basepath but it's not working as I would've imagined.

**Comment by sorxrob** [comment]
Hi @EmilTholin , can you do that with netlify? Thank you.

**Comment by sorxrob** [comment]
Okay solved it in netlify.

You can either

1. Create _redirects file and inside add `/* /index.html 200` then save it inside public folder.

2. Create a netlify.toml file in the root of your project and inside, add this 
```
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

**Comment by chovy** [comment]
This doesn't work on nginx.

**Comment by moritzebeling** [comment]
Just as an extension to @EmilTholin answer:

When you look inside the `serve()` function inside `rollup.config.js`, you can see, that `npm run dev` also triggers `npm run start` to start the server, which is Sirv in the default Svelte setup.

So go to your npm `package.json` and add the `--single` flag to the `start` command:
```json
"start": "sirv public --no-clear --single"
```

**Comment by lyf2000** [comment]
I have deployed nginx with built svelty app  and with `localhost/tasks7` query and
```
# ngninx.conf

server {

    listen 80;
    location / {
        root   /app;
        index  index.html;
        try_files $uri $uri/ $uri.html /index.html;
    }

}
```
I just get start page, without page of specific task, I know that I just redirect to start page, but solution like:
```
# ngninx.conf

server {

    listen 80;
    location / {
        root   /app;
        index  index.html;
        try_files $uri $uri/ $uri.html /index.html$is_args$args =404;
    }

}
```
Not works
