### ISSUE TITLE
Best practices for care some routes handler

### ISSUE THREAD

**Issue by DesdeChaves** [EmilTholin/svelte-routing#59]
I know that is possible to implement the authentication logic at the beginning of each route handler. In the following code the protected routes should only be visible after the user authentication.
 My concern is about the best pratices to care some routes handler. 

Is this the best approach to implement a separation between public and protected routes handler?

```
<script>
  import { Router, Route, navigate } from "svelte-routing";
  import NavLink from "./components/NavLink.svelte";
  import Home from "./routes/Home.svelte";
  import About from "./routes/About.svelte";
  import Login from "./routes/Login.svelte";
  import { currentUser } from "./stores/current_user.js";

  // Used for SSR. A falsy value is ignored by the Router.
  export let url = "";

  let showNav = false;

 $: if ($currentUser.token) {
      showNav = true
      navigate("/", { replace: true });
  } else {
      showNav = false
      navigate("/login", { replace: true });
  }

</script>

<Router url="{url}">

{#if showNav}
 <nav>
    <NavLink to="/">Home</NavLink>
    <NavLink to="about">About</NavLink>
  </nav>
{/if}

 <div>
    <Route path="/" component="{Home}" />
    <Route path="/about" component="{About}" />
    <Route path="/login" component="{Login}" />
  </div>

</Router>
```

**Comment by whiteadder** [comment]
From a newbie: 
i have this in my app.svelte

```
  import userAuth from "./stores/auth-store.js";
  userAuth.checkToken();
```

and this on my store 


```
checkToken: () => {
    if (localStorage.getItem('jwtToken')) {
      const decodedToken = jwtDecode(localStorage.getItem('jwtToken'));
      if (decodedToken.exp * 1000 < Date.now()) {
        localStorage.removeItem('jwtToken');
        navigate('/', { replace: true });
      } else {
        userAuth.set(decodedToken);
        navigate('/players', { replace: true });
      }
    } else {
      navigate('/', { replace: true });
    }
  }
```

seems to work

**Comment by EmilTholin** [comment]
Both of your suggestions looks good!

When https://github.com/EmilTholin/svelte-routing/issues/46 is fixed you will also be able to abstract the logic into a component called e.g. `ProtectedRoute`, but what you have is good as well.

**Comment by whiteadder** [comment]
That would be great, i have modified mine a bit, will edit later. Because iwas having a no redirect if I type the adress manualy, but this is a must, a protected route or something as, beforeEnter(), gj

**Comment by sayhicoelho** [comment]
I'd like to see `beforeEnter` to run some piece of code whenever routing starts.

**Comment by mefechoel** [comment]
I made a [`ProtectedRoute` example in the REPL](https://svelte.dev/repl/c81d8f3dff584065a82b2d3ea7cd4aee?version=3.29.0) for [svelte-navigator](https://github.com/mefechoel/svelte-navigator), which is a fork of svelte-routing. It won't completely work with svelte-routing, since it uses some of svelte-navigators newer features, but it should give you a starting point.

**Comment by dgellow** [comment]
@mefechoel I removed the slots, and used only one component, and arrived to the following (the `component` prop follows what `svelte-routing` does):

```svelte
<!-- RouteAuth.svelte -->

<script lang="ts">
        import { navigate, Route } from "svelte-routing"
        import { auth } from "../../stores/auth"

        export let path: string
        export let redirect: string = "login"
        export let component: any

        $: if (!$auth.id) {
                navigate(redirect, {
                        // replace: true,
                })
        }
</script>

<Route {path}>
        <svelte:component this={component} />
</Route>
```

And its use:
```svelte
<!-- Routing.svelte -->

<script lang="ts">
        import { Router, Route } from "svelte-routing"
        import Login from "./pages/Login.svelte"
        import App from "./App.svelte"
        import Error from "./pages/Error.svelte"
        import RouteAuth from "./components/routing/RequireAuth.svelte"
        import RouteNoAuth from "./components/routing/RequireNoAuth.svelte"

        export let appUrl = ""
</script>

<Router url={appUrl}>
        <Route path="error" component={Error} />
        <RouteNoAuth path="login" redirect="/" component={Login} />
        <RouteAuth path="/" redirect="login" component={App} />
        <Route path="*">
                <p>Not found</p>
        </Route>
</Router>
```

**Comment by mefechoel** [comment]
Looks good to me!
If you're using server side rendering you might need to wrap your `<svelte:component ... />` in an if block as well. `navigate` does not work in ssr, so the redirect won't work. A client who has js disabled and who is not logged in might see some protected content

**Comment by dgellow** [comment]
Hmm, then I'm doing something incorrect. I started with the `if` block around the wrapped component but for some reasons it doesn't seem to be rendered after a navigate (reloading the page renders it though).

```svelte
<!-- RouteAuth -->

<script lang="ts">
	import { navigate, Route } from "svelte-routing"
	import { auth } from "../../stores/auth"

	export let path: string
	export let redirect: string = "login"
	export let component: any

	$: if (!$auth.id) {
		navigate(redirect)
	}
</script>

<Route {path}>
	{JSON.stringify($auth)}
	{#if $auth.id}
		<svelte:component this={component} />
	{/if}
</Route>
```

A route protected with this component does correctly redirect to the `/login`, but results in an empty page.

**Comment by mefechoel** [comment]
Hmm, you could try to put the call to `navigate` in an `onMount`. Navigations that occure before the main `Router`'s mounting are swallowed (see [related issue in svelte-navigator](https://github.com/mefechoel/svelte-navigator/issues/16)). 
The problem is, that you'll loose the reactivity in onMount. So `afterUpdate` might be the better place to put it.
But because your component is always rendered, it will redirect on every route, when the user isn't logged in. That's why I put the guard in a second component inside the Route. That way, it is only rendered whe the route matches and only then redirects.

**Comment by dgellow** [comment]
@mefechoel Thank you so much, that's exactly what I was missing! 😸 ❤️

**Comment by kryptus36** [comment]
@tgf9 I think it's difficult to write one that's generic. Here's mine...the LoginForm component is a bootstrap modal window. currentUser is a svelte store. This way, when they log in, it takes them straight in, and straight back to login if they log out. It also uses either a passed in component or a slot for flexibility. But you could implement it in many other ways.

```
<script lang="ts">
  import { currentUser } from 'lib/shared-ui';

  import LoginForm from '../../components/modals/LoginForm.svelte';

  export let component = null;
</script>


{#await currentUser.fetch()}
  <Loading />
{:then}
  {#if $currentUser}
    {#if component !== null}
      <svelte:component this={component} />
    {:else}
      <slot />
    {/if}
  {:else}
    <LoginForm isOpen={true} toggle={() => {}} on:success={() => {location.reload()}} />
  {/if}
{/await}
```

Hope that's useful.
