### ISSUE TITLE
question: How do I get path parameters?

### ISSUE THREAD

**Issue by matryer** [EmilTholin/svelte-routing#60]
I have a route that looks like this:

```html
<Route path="/tests/:testname" component="{ViewTest}" />
```

I want to access the `:testname` value inside the `ViewTest` component but it wasn't obvious to me the best way to do this. Any help would be appreciated?

**Comment by gissleh** [comment]
I was wondering the same, and found out that if you `export let testname` in `ViewTest`, it will set that.

**Comment by matryer** [comment]
Thank you @gissleh I’ll give it a try.

**Comment by husnulhamidiah** [comment]
@gissleh I try to put export in my component, but when I try `console.log` it says undefined. Can you give us an example?

**Comment by vedmant** [comment]
This should be in readme, there is no example of how it supposed to work.

**Comment by gissleh** [comment]
The readme does say that (see below quote), but yeah, it could be clearer and shown in an example.

> All properties other than path and component given to the Route will be passed to the rendered component.

**Comment by matryer** [comment]
I think it's worth showing an example of this?

**Comment by LyndonDev** [comment]
I've found that the way to do this is as props are explained in the Svelte docs.

If you declare a route like so:
`<Route path="/:cat" component={Main}></Route>`

Inside of your main component, simply declare the prop:
```
<script>
  export let cat
</script>

<h1 class="title">Category = {cat}</h1>
```

**Comment by EmilTholin** [comment]
Hi @matryer!

Like @gissleh said you should export the variables from the component of the `Route`, since the path parameters will be passed to the rendered component.

This is [mentioned briefly in the documentation](https://github.com/EmilTholin/svelte-routing#route):

> Potential route parameters will be passed to the rendered `component` as properties.
