### ISSUE TITLE
How to get the current url?

### ISSUE THREAD

**Issue by aleksandrenko** [EmilTholin/svelte-routing#62]
How to get the current url?

**Comment by aleksandrenko** [comment]
The concrete case is to hide/show more the one component per path.

**Comment by danegigi** [comment]
I think you can use `window.location` for this.

**Comment by EmilTholin** [comment]
In [1.4.0](https://github.com/EmilTholin/svelte-routing/blob/master/CHANGELOG.md#140) we started to pass the `location` as a prop to the rendered Route `component` and slot.

You could do something like the following to automatically re-render when the current url changes:

```html
<!-- App.svelte -->
<Route path="blog" component="{Blog}" />

<!-- Blog.svelte -->
<script>
  export let location;
</script>

<h1>Blog</h1>
<p>{location.href}</p>
```

**Comment by farskid** [comment]
> I think you can use `window.location` for this.

using `window.location` won't work in cases in which you'd wanna access the updated location while you're staying on the same route.

Take a route with a query parameter for an example. Query parameter can update and in return update the location but since you're staying on the same route, you wouldn't get the upated query param if you're getting it from `window.location`. `location` prop passed to routes however will get the most updated one.

You just have to make sure you're using Reactive statements to get notified once the query parameter changes.

```js
// Route
<Route path="/test" component={Test} />

// Test.svelte
<script>
  import { Link } from "svelte-routing";
  export let location;

  $: queryParam = new URLSearchParams(location.search).get("id")
</script>

<p>{id}</p>
<Link
  to={`/test?id=${Math.random()}`}>
  Go to chat 1 normally
</Link>


```

**Comment by Zachiah** [comment]
Is it possible to watch the location in a store? Or globally in App.svelte? I'm trying to make my navbar close automatically when a linik is clicked. I could just wrap every page in a Page component, and add the watching code like mentioned above in page, although I would prefer to put in in a store or in App.svelte if possible. Thanks

**Comment by NekitCorp** [comment]
How to access a `Header` component that is outside `Route`? 

`<Router>
    <Header />
    <main>
        <Route path="/test1" component={Test1} />
        <Route path="/test2" component={Test2} />
        <Route path="/test3" component={Test3} />
    </main>
    <Footer />
</Router>`

maybe you can export the internal state with current url?

**Comment by Doomd** [comment]
Building on the excellent example provided by [NekitCorp](https://github.com/EmilTholin/svelte-routing/issues/62#issuecomment-760151657), here's what I did to have global access to the current url (assuming it was pushed to global history):

We'll use [stores](https://svelte.dev/tutorial/writable-stores): in "stores.js"
```
import { writable } from "svelte/store"
export const currentPath = writable("")
```

In `App.svelte`
```
<script>
import { currentPath } from "../path/to/stores.js"

...

onMount(() => {
    unsub = globalHistory.listen(({ location, action }) => {
      console.log(location, action)
      $currentPath = location.pathname
    })
  })

onDestroy(() => {
  unsub()
})
</script>
```

From any `Other.svelte` file:
```
<script>
import { currentPath } from "../path/to/stores.js"
// You can access the $currentPath variable in the scripting area...
function reportPath() {
  console.log(`The current path is:`, $currentPath)
}
</script>

...

<!-- Or in your HTML: -->
<h1>The current path is: {$currentPath}</h1>
```

From an `external.js` file:
```
import { currentPath } from "../js/all"

...

// Method #1 (Subscribe)
let path1
currentPath.subscribe(v => (path1 = v))
function reportPath1() {
  console.log(`path1:`, path1)
  return path1
}

// Method #2 (get)
import { get } from "svelte/store"
function reportPath2() {
  let path2 = get(currentPath)
  console.log(`path2:`, path2)
  return path2
}
```

**Comment by NekitCorp** [comment]
You can also add the initial state as ```export const currentPath = writable(window.location.pathname)``` :)

**Comment by Ladvace** [comment]
> How to get the current url in `Header` component that is outside `Route`?
> 
> ```js
> <Router>
>     <Header />
>     <main>
>         <Route path="/test1" component={Test1} />
>         <Route path="/test2" component={Test2} />
>         <Route path="/test3" component={Test3} />
>     </main>
>     <Footer />
> </Router>
> ```
> 
> maybe you can export the internal state with current url?
> 
> UPD: found a temporary workaround, maybe help someone:
> 
> ```js
> <script>
>     import { onDestroy, onMount } from 'svelte';
>     import { globalHistory } from 'svelte-routing/src/history';
> 
>     let pathname = window.location.pathname;
>     let unsub;
> 
>     onMount(() => {
>         unsub = globalHistory.listen(({ location, action }) => {
>             console.log(location, action);
>             pathname = location.pathname;
>         });
>     });
> 
>     onDestroy(() => {
>         unsub();
>     });
> </script>
> 
> <header>{pathname}</header>
> ```

it doesn't work for me, I get listen of undefined

**Comment by faisalakhlaq** [comment]
> This will work for sveltekit:
> 
> ```
> 
> <script lang="ts">
>     import { page } from '$app/stores';
>     
>     import { onMount } from 'svelte';
>     
>     onMount(async () => {
> 			
> if($page.path === '/' || $page.path === '/tags') {  
> 
> })
> }
> 
> you can get your main web page address and combine it:
> 
> config.website + $page.path 
> ```

page.path is replaced by $page.url.searchParams

**Comment by bitdom8** [comment]
Updating, thanks @faisalakhlaq

**Comment by dawidjaniga** [comment]
You can also use `useLocation` from 'svelte-routing` since version **1.8.0**:

`
  import { useLocation } from "svelte-routing";
  
  let location = useLocation();
  
  $: console.log($location);
`

Other context are also exported: `useHistory`, `useRouter`.

Details:
https://github.com/EmilTholin/svelte-routing/blob/e2e887a4d074a484319bae40514949bd0ee8cbc7/src/contexts.js

**Comment by wassilis83** [comment]
> @aleksandrenko You can also use `useLocation` from svelte-routing since version **1.8.0**:
> 
> ```js
>   import { useLocation } from "svelte-routing";
>   
>   let location = useLocation();
>   
>   $: console.log($location);
> ```
> 
> Other contexts are also exported: `useHistory`, `useRouter`.
> 
> Details: https://github.com/EmilTholin/svelte-routing/blob/e2e887a4d074a484319bae40514949bd0ee8cbc7/src/contexts.js

Dear why this is not working in app.svelte? Looks like is working only in components. Furthermore I need to retrieve the current path inside a store that is returning some data and I don't want them to be available on specific paths.
