### ISSUE TITLE
Active class for a link

### ISSUE THREAD

**Issue by vedmant** [EmilTholin/svelte-routing#63]
What's official approach to add "active" class to a link? I couldn't find any examples.

**Comment by EmilTholin** [comment]
Hi @vedmant!

You can give a function to the [`getProps` prop on the `Link` component](https://github.com/EmilTholin/svelte-routing#link) that returns an object that will be spread on the underlying anchor tag.

The example project in this repository has a [`NavLink` component demonstrating how this can be used](https://github.com/EmilTholin/svelte-routing/blob/master/example/src/components/NavLink.svelte).

**Comment by vedmant** [comment]
Wow, that's really overcomplicated, I just switched to https://github.com/ItalyPaleAle/svelte-spa-router as it's much more approaching.

**Comment by EmilTholin** [comment]
Yeah, it's a bit more work for just an active class, but it's flexible if you need something beyond that.

I am getting really tired of your bully tone and attitude. One more time and I will have you blocked from this issue tracker.

**Comment by mvllow** [comment]
Just wanted to say thank @EmilTholin for the great router, this issue helped me get active classes working. I was wondering, though, is there a way to use getProps when doing `<a use:link>` syntax?

As far as what @vedmant said... it is really not complicated, especially when using es6 syntax.

```
const getProps = ({ href, isPartiallyCurrent, isCurrent }) => {
    const isActive = href === "/" ? isCurrent : isPartiallyCurrent || isCurrent;
    return isActive ? { class: "active" } : {};
};
```

**Comment by EmilTholin** [comment]
Hi @mvllow! Thank you for your kind words!

There is sadly no way to use `getProps` when using the `link` action since Svelte actions are just functions that are called when the element is created, and actions don't have access to component props.

**Comment by vedmant** [comment]
Just FYI here is how it's done in svelte-spa-router https://github.com/ItalyPaleAle/svelte-spa-router#highlight-active-links easy and simple:
```
<a href="/hello/user" use:link use:active={'/hello/*', 'active'}>Say hi!</a>
<a href="/hello/user" use:link use:active>Say hi again!</a>
```

**Comment by colllin** [comment]
I tried a few things. It got a bit complicated. I ended up with this clunky but simple solution:

```
<script>
export let location;
let isPartiallyCurrentPath = (href) => location.pathname.substring(href.length) === href;
let isCurrentPath = (href) => location.pathname === href;
let isActivePath = (href) => isCurrentPath(href) || isPartiallyCurrentPath(href);
let paths = {
    cars: '/cars',
    drivers: '/drivers',
};
</script>

<a href={paths.cars} class="button" class:active={isActivePath(paths.cars)}>
    Cars
</a>
<a href={paths.drivers} class="button" class:active={isActivePath(paths.drivers)}>
    Drivers
</a>

<style>
.button { color: blue; }
.button.active { color: black; }
</style>
```

**Comment by kevinrenskers** [comment]
My solution, as a complete noob with Svelte (started a few hours ago). So please be kind :)

StoreLocation.svelte:

```
<script>
  import { getContext } from 'svelte';
  import { ROUTER } from 'svelte-routing/src/contexts';
  import { location } from './store.js';
  const { activeRoute } = getContext(ROUTER);

  $: {
    location.set($activeRoute);
  }
</script>
```

store.js:

```
import { writable } from 'svelte/store';
export const location = writable("");
```

actions.js:

```
import { location } from './store.js';

export function active(node) {
  let unsubscribe = location.subscribe(value => {
    node.classList.remove('active');
    if (node.href === window.location.href) {
      node.classList.add('active');
    }
  });

  return {
    destroy() {
      unsubscribe();
    }
  };
}
```

App.svelte:

```
<script>
  import { Router, Route, Link } from "svelte-routing";

  import Home from "./routes/Home.svelte";
  import Navbar from "./Navbar.svelte";
  import StoreLocation from "./StoreLocation.svelte"
</script>

<Router>
  <div id="container">
    <StoreLocation />
    <Navbar {user} {status} />
    <main>
      <Route path="/"><Home {user} {status} /></Route>
    </main>
  </div>
</Router>
```

And with all that in place, I can now use my own custom `use:active` action everywhere. For example in my `Navbar` component:

```
<script>
  import { link } from "svelte-routing";
  import { active } from './actions';
</script>

<nav>
  <a use:link use:active href="/">Home</a>
  <a use:link use:active href="/another-thing">Another thing</a>
</nav>

<style>
  nav :global(a.active) {
    font-weight: bold;
  }
</style>
```

The setup is a bit of a hassle, but once you have that in place, it's very easy to use `use:active` everywhere (as long as you use it on an `a` tag, so normally in combination with `use:link`). Of course it's super simple, no config, no partial matches or whatever, but for now this works for me :)

**Comment by Trolzie** [comment]
@vedmant  This solution I think is more elegant than adding a class.

I noticed that the active link gets an `aria-current="page"`.
So the way I styled it was by doing: `a[aria-current="page"] { color: green; }`

I did run into problems since the anchor `<a>` isnt represented in the html because we are using the <Link /> component. so I am currently doing this:

`  :global(a[aria-current="page"]) {
    border-bottom: 1px solid grey;
  }`

Im not fond of polluting the global namespace, so I'm searching for a better way to target the anchor.

**Comment by sharu725** [comment]
Isn't this the way?
``` html
<script>
  import { link } from "svelte-routing";
</script>

<Router>
  <a href="/" use:link>Home</a>
<Router>
```
 [https://github.com/EmilTholin/svelte-routing#link-1](https://github.com/EmilTholin/svelte-routing#link-1)

**Comment by phiphou** [comment]
@vedmant If you think programming is just adding a class, so you don't really know what it is. Svelte routing and svelte-spa-router are two solutions for routing in svelte but svelte-spa-router use a hash based solution, which is in my opinion an issue.

**Comment by vedmant** [comment]
@phiphou It's called a good programming when you just need to add a class instead of creating extra functions and repeating code. For the router this is one of the most commonly used feature (to highlight active links), and the most common way to change styles is by using css classes. You can find docs about this in most popular routers (https://router.vuejs.org/api/#active-class, https://reactrouter.com/web/api/NavLink/activeclassname-string).

**Comment by phiphou** [comment]
You want a simple solution ? You have one with this library. Not a single class but 4 lines in a dedicated component. Both solution are simple to implement. And you're not forced to use a hash bases solution like svelte-spa-router. Another point : your behavior. You could have propose a nicer solution, mentioning svelte-spa-router's one, but politely. Maybe it would have be taken in account by the author.
