### ISSUE TITLE
How do I get the params from Route?

### ISSUE THREAD

**Issue by danegigi** [EmilTholin/svelte-routing#65]
Here's what I'm planning to do

1. Retrieve the ID number of the user that (user/**:id**/edit)
2. After a successful save **dispatch** an event that the parent component (App.svelte) will process

App.svelte
```
<script>
     let showModal = false;
     let msg='';
     async function showModal(event){
         msg = event.detail;
         showModal=true
     }
</script>
{#if showModal }
    <Modal {msg} />
{/if}
<Router>
    <Route path="/user/:id/edit">
       <UserEdit on:success="{showModal}" />
    </Route>
    // some other route
</Router>

```

UserEdit.svelte
```
  <script>
    export let id; // UNDEFINED
    asyn function onSubmit(){
     dispatch('success', 'som message')
   }
  </script>
  ....
```
--------------------
In Route.svelte shows that there's no way to do this since it using slot and it's not passing any props
```
{#if $activeRoute !== null && $activeRoute.route === route}
  {#if component !== null}
    <svelte:component this="{component}" {...routeParams} {...routeProps} />
  {:else}
    <slot></slot>
  {/if}
{/if}
```

Is it possible to pass the parameters in the slot or expose the variables inside contexts.js if I want to use getContext.

Thanks

**Comment by EmilTholin** [comment]
Hi @danegigi!

There is currently no way to pass the path parameter to the slotted content. [There is a PR with a potential solution to this](https://github.com/EmilTholin/svelte-routing/pull/64) that will be looked at soon.

In the meantime you could take advantage of that all extra properties given to the `Route` will be passed to the rendered component.

```html
<!-- App.svelte -->
<Router>
  <Route path="/user/:id/edit" component="{UserEdit}" onSuccess="{showModal}" />
  <!-- ... -->
</Router>

<!-- UserEdit.svelte -->
<script>
  export let id;
  export let onSuccess;

  async function onSubmit(){
    onSuccess('some message');
  }
</script>
```

**Comment by danegigi** [comment]
Yes, I saw the pull request and it looks good. Waiting for it to be accepted. 

Thanks

**Comment by EmilTholin** [comment]
This functionality was added in `1.3.0`.
