### ISSUE TITLE
How to do transitions?

### ISSUE THREAD

**Issue by jaysson** [EmilTholin/svelte-routing#66]
I want to do route transitions similar to iOS view controller animations (slide in from right on push above current component, slide out on pop). Any options/guidelines?

**Comment by EmilTholin** [comment]
Hi @jaysson!

You can use Svelte's own built-in transitions on the component given as the `component` prop to one of the `Route` components and Svelte will animate it in/out.

You could e.g. create a component like this that you use as a top-most wrapper for all your `Route` components.

```html
<script>
  import { fade } from 'svelte/transition';
</script>

<div in:fade>
  <slot />
</div>

<style>
  div {
    position: absolute;
  }
</style>
```

**Comment by jaysson** [comment]
I will need to display 2 route components simultaneously till the animation is complete. I don't see a way to do it. The pushed route's component will slide on top of the current route component (like a stack). That's how iOS view controller push transition looks.

**Comment by EmilTholin** [comment]
Then you will need a slightly more complex setup than my example above. You can play around with [`delay` and `duration`](https://svelte.dev/docs#fade) for the different built-in transitions or create your own.

**Comment by ollyde** [comment]
The native iOS swipe back and Android back button will also mess this up fyi.
