### ISSUE TITLE
Support client side routing

### ISSUE THREAD

**Issue by neetjn** [EmilTholin/svelte-routing#67]
I'd like to request for client side routing support. It should be as simple as providing some opt with the `Router` component, a flag really. Then operating off this flag to decide between $location.path and $location.hash @ https://github.com/EmilTholin/svelte-routing/blob/master/src/Router.svelte#L103

**Comment by neetjn** [comment]
Proposed changes: https://github.com/EmilTholin/svelte-routing/pull/68

**Comment by EmilTholin** [comment]
Hi @neetjn!

The hash routing was removed in `1.0.0` as it opens up a can of worms of other issues, and it's not reasonable/desired for our small team to try and fit all those edge cases into the same library to try and make everyone happy.

You can use your own fork or something like [abstract-state-router](https://github.com/TehShrike/abstract-state-router/) to use hash-based routing with Svelte.

See https://github.com/EmilTholin/svelte-routing/issues/24
