### ISSUE TITLE
How to re-render a route when the query string changes?

### ISSUE THREAD

**Issue by brielov** [EmilTholin/svelte-routing#69]
Suppose you have a search form and when it gets submitted it updates the query string using navigate. How could I trigger a fetch to an API when the query changes?

**Comment by brielov** [comment]
Nobody?

**Comment by kfreiman** [comment]
Here is one possible method https://github.com/EmilTholin/svelte-routing/issues/41#issuecomment-503462045

**Comment by EmilTholin** [comment]
In [1.4.0](https://github.com/EmilTholin/svelte-routing/blob/master/CHANGELOG.md#140) we started to pass the `location` as a prop to the rendered Route `component` and slot.

You could do something like the following to automatically re-render when the query string changes:

```html
<!-- App.svelte -->
<Link to="blog?foo=bar">Blog</Link>
<Route path="blog" component="{Blog}" />

<!-- Blog.svelte -->
<script>
  import queryString from "query-string";

  export let location;

  let queryParams;
  $: queryParams = queryString.parse(location.search);
</script>

<h1>Blog</h1>
<p>{queryParams.foo}</p>
```
