### ISSUE TITLE
basepath not working

### ISSUE THREAD

**Issue by hudsonvalleycloudcomputing** [EmilTholin/svelte-routing#70]
```
<script>
  import { Router, Link, Route } from "svelte-routing";

  import LifeGoalsDisplay from "./LifeGoalsDisplay.svelte";
  import About from "./About.svelte";
  import Contact from "./Contact.svelte";

  export let url = "";
  export let basepath = "/static";
</script>

<Router basepath={basepath} url={url}>
  <Route path="/about" component={About} />
  <Route path="/contact" component={Contact} />
  <Route path="/" component={LifeGoalsDisplay} />
</Router>
```
----------------------
For the above only http://localhost:8080/static works but not http://localhost:8080/static/about or http://localhost:8080/static/contact

The same works if I output everything to public folder (default rollup.config.js) and if I remove the basepath

I changed rollup.config.js to output everything to the public/static folder and changed as shown above and now it doesn't pickup /about and /contact

Am I missing something?

**Comment by EmilTholin** [comment]
Hi @hudsonvalleycloudcomputing!

I just tested your code using the [example in this repository](https://github.com/EmilTholin/svelte-routing/tree/master/example) and the `basepath` is working fine. Do you think you could create a minimal example and put it on GitHub that I could clone and take a look at?

**Comment by hudsonvalleycloudcomputing** [comment]
Hi Emil,

I put back the default rollup.config.js and only added the basepath to the router and it worked as documented (it routed to /static/about and /static/contact using the npm dev server). 

I still cannot get it to work when I build the project and move it to the static directory of appengine project (golang appengine project) but you can close this issue for now.

Thanks

**Comment by EmilTholin** [comment]
Alright, great!

I'm not sure what might be the issue, but it might be that appengine doesn't serve the `index.html` file all your routes, but only for the main `/static` route. Might be worth looking into.

**Comment by rushirufu** [comment]
> Hi @hudsonvalleycloudcomputing!
> 
> I just tested your code using the [example in this repository](https://github.com/EmilTholin/svelte-routing/tree/master/example) and the `basepath` is working fine. Do you think you could create a minimal example and put it on GitHub that I could clone and take a look at?

404 - page not found
