### ISSUE TITLE
router does not redirect

### ISSUE THREAD

**Issue by sinistra** [EmilTholin/svelte-routing#71]
I'm getting an issue where a call to 'navigate()' does not complete. 
The code appears to just die.

Here is the function that is being called ...

` function siteEdit(event) {  
    site = event.detail;  
    console.log(site);  
    navigate("/sites/edit", { replace: false });  
  }  
`

and here is the Route definition ...
`   <Route path="/sites/edit">  
      <SiteEdit macdsite={site} on:save={saveSite} on:cancel={cancelSite} />  
    </Route>  
`

when the siteEdit function is called, the console.log(site) statement executes and prints the object in the console, but the next statement does not execute. The app appears to skip this command.

The menu works for other links.

Can anyone tell me if I have done something wrong?

**Comment by EmilTholin** [comment]
Hi @sinistra!

Could you please create a minimal reproducible example on GitHub that we can ideally just clone and run `npm install && npm start` to test? It's hard to say what might be wrong without more context or code to look at.

**Comment by sinistra** [comment]
Thanks for the reply.
I've extracted the code into a separate repo and pushed to https://github.com/sinistra/macd
The code calls an api, so while it will compile & run, it will be difficult to test.

My problem is demonstrated in Apps.svelte, line 39 function siteEdit(event).

The workflow is user executes line 128 ...
`<Route path="/sites">  
      <Sites on:siteEdit={siteEdit} />  
  </Route>`

This bubbles an event up to Apps.svelte. The event contains an object (the selected record).
siteEdit is called passing in the object. The object is successfully logged to the console @ line 42.
next call is line 43 ... navigate("/sites/edit", { replace: false });
This line does not execute.

If you think I'm doing something wrong or can suggest a better way to use svelte-routing, I am happy to hear it.

**Comment by sinistra** [comment]
Hi Emil,
I put a consol.log('here') into SiteEdit.svelte.
I can enter the url http://localhost:5000/sites/edit and 'here' is displayed in the console log.
But nothing is displayed when `navigate("/sites/edit", { replace: false });` is called.

**Comment by sinistra** [comment]
I started tracing the js with the browser debugger and found the call to navigate completed and handed off to click_eventHandler(). This looks like svelte, not the router.
So I put a console.log in after the navigate() call.
Now this console message is appearing in the console.log and the <SiteEdit> component is being called.

I'm suspect I may have exposed a potential bug in svelte, not the router.

Thank you for your help, but I don't think this is a router issue.

However, would you mind reviewing my implementation of the router and comment if you think I could do things better?

**Comment by EmilTholin** [comment]
Great that you figured out what the issue was!

The code looks good!
