### ISSUE TITLE
Client logs on server

### ISSUE THREAD

**Issue by airandopal** [EmilTholin/svelte-routing#78]
Hi there, 
Are client side logs supposed to be showing on the server? If so, how can I turn this off? I have turned the env vars for NODE_ENV and ROLLUP_WATCH to production mode settings, and I'm still getting them. You can see here on [this app](https://glitch.com/edit/#!/join/b36d3352-2f20-416c-a220-e08f3240e4d1) that the console.log from the Home Route is showing in the server logs.

**Comment by EmilTholin** [comment]
Hi @airandopal!

Yes, code directly inside the script tag will be run on the server as well.

You can get around this by putting code you only want to run in the browser in the `onMount` hook.

```html
<script>
  import { onMount } from "svelte";

  onMount(() => {
    console.log("a log from the browser");
  });
</script>

<h1>Home</h1>
<p>Welcome to my website</p>
```

You could also create logging helper functions that check for the existence of `window` before logging to only run it in the browser.

```js
// logger.js
export function log(msg) {
  if (typeof window !== "undefined") {
    console.log(msg);
  }
}
```
```html
<!-- Home.svelte -->
<script>
  import { log } from "./logger.js";

  log("a log from the browser");
</script>

<h1>Home</h1>
<p>Welcome to my website</p>
```
