### ISSUE TITLE
use:link does not pass query params to the next route

### ISSUE THREAD

**Issue by parkerqueen** [EmilTholin/svelte-routing#79]
Whenever I use an anchor tag with a "use:link" attribute, the query params specified in the href attribute are not passed on.

`<a use:link href="/partners?roger=true">Foobar</a>`

Here the app routes to the '/partners' route correctly but the roger query param isn't available in location.search.

**Comment by parkerqueen** [comment]
bump

**Comment by cibernox** [comment]
This is also super annoying

**Comment by chasm** [comment]
Anchors are not included either. I would like to link into a page without forcing a reload. Maybe can do this with `navigate`, but would be nice to do it with `use:link` as well.

**Comment by chovy** [comment]
This router sucks guys. I suggest you use `svelte-spa-router` it has a similar api

**Comment by EmilTholin** [comment]
This nice addition has been released in `1.4.1`.

**Comment by QuantumInformation** [comment]
I tried the following:

            <Route path="profile/:username" component={Profile} />

and using

    <a use:link href="{`profile?username=${user.username}`}">
        <span>{user.displayName || user.uid}</span>
    </a>

but the route doesn't get hit:


![image](https://user-images.githubusercontent.com/216566/77825388-3e2cf700-7109-11ea-8fad-9b7209372302.png)

what  am I missing

**Comment by QuantumInformation** [comment]
<Route path="profile" component={Profile} />
will end up at the route, without the params:

![image](https://user-images.githubusercontent.com/216566/77828313-f1521c00-711a-11ea-8a45-b6c3be48c56a.png)
