### ISSUE TITLE
Svelte Context API not working in Nested Routes

### ISSUE THREAD

**Issue by yousufiqbalhashim** [EmilTholin/svelte-routing#80]
I've a function defined in `setContext('getIstiftas', getIstiftas)` in Parent Route and later in Child Route is was called using `getContext('getIstiftas')` and then `await getIstiftas()` inside async function. But Chrome is displaying ..

`Uncaught (in promise) TypeError: getIstiftas is not a function`

**Comment by yousufiqbalhashim** [comment]
There was an own mistake from my side.

**Comment by EmilTholin** [comment]
Hey @yousufiqbalhashim! Great that you solved it!
