### ISSUE TITLE
history.js - Edge support

### ISSUE THREAD

**Issue by Skillcrafter0307** [EmilTholin/svelte-routing#82]
`history.js` uses the "new" Spread syntax which is not supported in Edge.

```javascript 
function getLocation(source) {
  return {
    ...source.location,
    state: source.history.state,
    key: (source.history.state && source.history.state.key) || "initial"
  };
}
```

and I'm just to dumb to fix it maybe you can help me.

**Comment by EmilTholin** [comment]
Hi @Skillcrafter0307!

There are quite a lot of modern JavaScript features used in this library. You can use something like [Bublé](https://buble.surge.sh/guide/) or [Babel](https://babeljs.io/) to transpile the code to JavaScript that is supported by older browsers.
