### ISSUE TITLE
Async fetching does not work

### ISSUE THREAD

**Issue by viper6277** [EmilTholin/svelte-routing#84]
This may be related to issue #46 I'm not sure... but I cannot get the remote endpoint to be called. and I see a error in console that reads...

"Route.svelte:40 Uncaught (in promise) TypeError: Cannot read property 'parentNode' of undefined"

Once I take svelte-routing out of the mix, and I have a the fetch component called directly from App.svelte the endpoint is called and the data is fetched and displayed. 

Fetch.svelte
```javascript
<script>
  import { onMount } from "svelte";
  
  export let url;
  
  let jsonResponse = [];
  
  onMount(async function() {
    const response = await fetch(url);
    const json = await response.json();
    jsonResponse = json;
    console.log(jsonResponse);
  });

</script>

<slot {jsonResponse} />
```

Api.svelte
```javascript
<script>
  import Fetch from "../components/Fetch.svelte";
</script>

<Fetch let:jsonResponse url={"API ENDPOINT"}>
  <h1>list</h1>
  <ul>
    {#each jsonResponse as item}
      <li>
        <p>{item.title}</p>
      </li>
    {/each}
  </ul>
</Fetch>
```
App.svelte
```javascript
<script>
  import { Router, Route } from "svelte-routing";
  import Nav from "./components/Navigation.svelte";
  import AppRouter from "./AppRouter.svelte";
  export let url = "";
</script>

<Router url="{url}">
  <Nav/>
  <AppRouter></AppRouter>
</Router>
```

AppRouter.svelte
```javascript
<script>
  import { Route } from "svelte-routing";
  import Home from "./routes/Home.svelte";
  import Api from "./routes/Api.svelte";
</script>  

<!-- The padding is there to accomodate to top bar height-->
<div class="w3-container" style="padding-top:100px;" id="app_router">
  <Route path="/" component="{Home}" />
  <Route path="api" component="{Api}" />  
</div>
```

**Comment by EmilTholin** [comment]
Hi @viper6277!

https://github.com/EmilTholin/svelte-routing/issues/46 was just closed since it was fixed upstream in `svelte@3.16.5`. Could you try the code above again with that Svelte version and see if that helps? If not, could you create a minimal reproducible example that I can clone and try on my machine?
