### ISSUE TITLE
Deploying app on Netlify or Now doesn't work with the router

### ISSUE THREAD

**Issue by MartijnKeesmaat** [EmilTholin/svelte-routing#86]
I would like to deploy my project with Netlify or Now, but I keep getting an error. I also deployed the [example](https://github.com/EmilTholin/svelte-routing/tree/master/example), to make sure that I didn't make a mistake in my code.

It works locally but when I deploy the app, I see this error:
```Uncaught (in promise) TypeError: Cannot read property 'parentNode' of undefined```

It's possible that the problem is with the `target` since it doesn't seem to target anything? At least for what I see.
```
import App from "./App.svelte";

new App({
  target: document.getElementById("app"),
  hydrate: true
});
```

**Comment by EmilTholin** [comment]
Hi @MartijnKeesmaat! If there is no element in the document with id `app` you will get the error `Uncaught Error: 'target' is a required option`, so I don't think that's related to your issue.

It's hard to say what might be wrong without a minimal reproducible example I can look at.

**Comment by MartijnKeesmaat** [comment]
Hey, @EmilTholin thanks for taking the time to answer! I am going to close this issue since I think that the problem doesn't come from your plugin. The problem happens somewhere in the build process.

**Comment by sw-yx** [comment]
if you need netlify help hit me up

**Comment by MartijnKeesmaat** [comment]
@sw-yx Thanks for the offer! The problem, however, was with the build tool. Something went wrong when I used Rollup. Then I switched to Webpack and everything worked.
