### ISSUE TITLE
Problem with refreshing when using svelma components

### ISSUE THREAD

**Issue by Blm0423** [EmilTholin/svelte-routing#88]
When clicking on links in the NavBar, it does not refresh content if svelma components are on the page. Removing them and everything works normal.

App.svelte
```
<Router url="{url}">
  <nav>
    <NavLink to="/">[Logo]</NavLink>
    <NavLink to="search">Search</NavLink>
    <NavLink to="owner">Owner</NavLink>
    <NavLink to="property">Property</NavLink>
  </nav>
  <div>
    <Route path="search" component="{Search}" />
    <Route path="owner" component="{Owner}" />
    <Route path="property" component="{Property}" />
    <Route path="/" component="{Home}" />
  </div>
</Router>
```

Search.svelte
```
<script>
  import { Field, Input } from 'svelma'
</script>

    <Field label="Name">
      <Input value="Rich Harris" />
    </Field>
´´´

**Comment by EmilTholin** [comment]
Hi @Blm0423!

It's hard to say what the problem might be without more context. Do you think you could create a minimal reproducible example that we could ideally just clone and try?

**Comment by Blm0423** [comment]
I have uploaded a minimal example project, just discovered I was suing swedish text inside of it.
https://github.com/Blm0423/svelma-router-problem.git

Shifting between Home and About works fine, but when going to the Blog page (with Svelma components) and then click on Home will only update the URL but not the page content.

Från: Emil Tholin <notifications@github.com>
Skickat: den 14 november 2019 00:42
Till: EmilTholin/svelte-routing <svelte-routing@noreply.github.com>
Kopia: Jan Blomqvist <jan.blomqvist@advox.se>; Mention <mention@noreply.github.com>
Ämne: Re: [EmilTholin/svelte-routing] Problem with refreshing when using svelma components (#88)


Hi @Blm0423<https://github.com/Blm0423>!

It's hard to say what the problem might be without more context. Do you think you could create a minimal reproducible example that we could ideally just clone and try?

**Comment by EmilTholin** [comment]
Thanks! I'm from Sweden, so the Swedish description is no problem.

I get the same error when trying the code in `Blog.svelte` without the router involved. It seems to have something to do with [this line](https://github.com/c0bra/svelma/blob/d4ce88cbcf35921a4e66fd026d934f90591cb42b/src/components/Field.svelte#L70) and `el` being `undefined`. I'm not sure if it's a bug in Svelma or Svelte.
