### ISSUE TITLE
links.js - IE support

### ISSUE THREAD

**Issue by kaisermann** [EmilTholin/svelte-routing#9]
`links.js` uses `Element.prototype.closest` which is [not supported in IE](https://developer.mozilla.org/pt-BR/docs/Web/API/Element/closest) and some older versions of major browsers.

Since it's a simple operation, can we replace it with something like this?

```js
function findClosest(tagName, el) {
	while(el && el.tagName !== tagName) el = el.parentNode
	return el
}
```

```js
function onClick(event) {
	const anchor = findClosest('A', event.target)
	...
```

**Comment by EmilTholin** [comment]
Absolutely. Feel like making a PR?

**Comment by kaisermann** [comment]
Yep. there you have it ;)
