### ISSUE TITLE
store.subscribe is not a function

### ISSUE THREAD

**Issue by christopherbecker** [EmilTholin/svelte-routing#92]
Hi,

Implementing does not work, I get an error.

The following error using the latest svelte 3.16.3:

```
TypeError
store.subscribe is not a function
subscribe
https://1od9o.csb.app/node_modules/svelte/internal/index.js:45:25
instance
src/Router.svelte:14:28
  11 | const locationContext = getContext(LOCATION);
  12 | const routerContext = getContext(ROUTER);
  13 | 
> 14 | const routes = writable([]);
```

I can confirm that the error goes away and the library works when I switch to svelte 3.12.0

**Comment by EmilTholin** [comment]
Hi @christopherbecker!

That's frustrating. There is not enough information in your issue for anyone to help you though. `svelte@3.16.3` works in the [example in this repository](https://github.com/EmilTholin/svelte-routing/tree/master/example), so please include a minimal reproducible example that we can clone and try.

**Comment by christopherbecker** [comment]
Hi Emil,

Here is a sandbox: https://codesandbox.io/s/snowy-sea-1od9o

Thanks,
Christopher

**Comment by EmilTholin** [comment]
It works if you uninstall svelte and install it again in that sandbox. I'm closing this issue as it is CodeSandbox-related and not an issue with `svelte-routing`.

**Comment by christopherbecker** [comment]
It is now working in codesandbox, someone must've fixed something.
