### ISSUE TITLE
Question: Initial History

### ISSUE THREAD

**Issue by clintwood** [EmilTholin/svelte-routing#93]
Great module - thank you :pray: 

Given a router setup like so:
```html
<script>
  ....
  export let url = '/main';
</script>

<Router {url}>
  <Route path="/intro/*wcUrl" component={IntroLayout} />
  <Route path="/profile/*wcUrl" component={ProfileLayout} />
  <Route path="/main/*wcUrl" component={MainLayout} />
</Router>
```
From what I'm seeing although the router correctly navigates to `'/main'` (assuming no `url` prop was passed) the first history entry remains pointing to `'/'` - is this expected behavior or a bug?

What is the best practice for ensuring that the initial history entry is the value of `url`?

What I've done as a workaround is the following:
```html
<script>
  ....
  export let url = '/main';
  onMount(() => {
    navigate(url, { replace: true });
  });
</script>
```

**Comment by EmilTholin** [comment]
Hi @clintwood! Thank you for the kind words.

> From what I'm seeing although the router correctly navigates to `'/main'` (assuming no `url` prop was passed) the first history entry remains pointing to `'/'` - is this expected behavior or a bug?

This is expected behaviour. The `url` prop is only supposed to be used in SSR to give the `Router` the current url as there is no browser location to read it from.

> What is the best practice for ensuring that the initial history entry is the value of `url`?

I think your workaround seems reasonable, but it is a browser redirect to `/main`.

**Comment by clintwood** [comment]
Thanks for your feedback - the workaround seems to be working fine!
