### ISSUE TITLE
Block template on navigate from continuing 

### ISSUE THREAD

**Issue by QuantumInformation** [EmilTholin/svelte-routing#96]
I often do stuff like this to navigate away from a route on certain conditions

![image](https://user-images.githubusercontent.com/216566/71518209-7169ab00-28ba-11ea-9357-cd49922d9d8f.png)

however, this will throw an error because     `let email = $authUserStore.email` will still be executed.

Is there a way to avoid executing code after a navigate or will I have to write conditional code after this?

**Comment by divmgl** [comment]
`return`?

**Comment by QuantumInformation** [comment]
this was my solution

https://github.com/QuantumInformation/svelte-fullstack-starter/blob/master/src/components/Authenticated.svelte#L5

return didnt work
